// Code generated by ent, DO NOT EDIT.

package componentattr

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the componentattr type in the database.
	Label = "component_attr"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldComponentID holds the string denoting the component_id field in the database.
	FieldComponentID = "component_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// EdgeComponent holds the string denoting the component edge name in mutations.
	EdgeComponent = "component"
	// Table holds the table name of the componentattr in the database.
	Table = "component_attribute"
	// ComponentTable is the table that holds the component relation/edge.
	ComponentTable = "component_attribute"
	// ComponentInverseTable is the table name for the Component entity.
	// It exists in this package in order to avoid circular dependency with the "component" package.
	ComponentInverseTable = "component"
	// ComponentColumn is the table column denoting the component relation/edge.
	ComponentColumn = "component_id"
)

// Columns holds all SQL columns for componentattr fields.
var Columns = []string{
	FieldID,
	FieldComponentID,
	FieldName,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(string) error
)

// OrderOption defines the ordering options for the ComponentAttr queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByComponentID orders the results by the component_id field.
func ByComponentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComponentID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByComponentField orders the results by component field.
func ByComponentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newComponentStep(), sql.OrderByField(field, opts...))
	}
}
func newComponentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ComponentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ComponentTable, ComponentColumn),
	)
}
