// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/stackmon/otc-status-dashboard/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/componentattr"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/incidentstatus"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Component is the client for interacting with the Component builders.
	Component *ComponentClient
	// ComponentAttr is the client for interacting with the ComponentAttr builders.
	ComponentAttr *ComponentAttrClient
	// Incident is the client for interacting with the Incident builders.
	Incident *IncidentClient
	// IncidentStatus is the client for interacting with the IncidentStatus builders.
	IncidentStatus *IncidentStatusClient
	// NotificationOutbox is the client for interacting with the NotificationOutbox builders.
	NotificationOutbox *NotificationOutboxClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Component = NewComponentClient(c.config)
	c.ComponentAttr = NewComponentAttrClient(c.config)
	c.Incident = NewIncidentClient(c.config)
	c.IncidentStatus = NewIncidentStatusClient(c.config)
	c.NotificationOutbox = NewNotificationOutboxClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Component:          NewComponentClient(cfg),
		ComponentAttr:      NewComponentAttrClient(cfg),
		Incident:           NewIncidentClient(cfg),
		IncidentStatus:     NewIncidentStatusClient(cfg),
		NotificationOutbox: NewNotificationOutboxClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Component:          NewComponentClient(cfg),
		ComponentAttr:      NewComponentAttrClient(cfg),
		Incident:           NewIncidentClient(cfg),
		IncidentStatus:     NewIncidentStatusClient(cfg),
		NotificationOutbox: NewNotificationOutboxClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Component.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Component.Use(hooks...)
	c.ComponentAttr.Use(hooks...)
	c.Incident.Use(hooks...)
	c.IncidentStatus.Use(hooks...)
	c.NotificationOutbox.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Component.Intercept(interceptors...)
	c.ComponentAttr.Intercept(interceptors...)
	c.Incident.Intercept(interceptors...)
	c.IncidentStatus.Intercept(interceptors...)
	c.NotificationOutbox.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ComponentMutation:
		return c.Component.mutate(ctx, m)
	case *ComponentAttrMutation:
		return c.ComponentAttr.mutate(ctx, m)
	case *IncidentMutation:
		return c.Incident.mutate(ctx, m)
	case *IncidentStatusMutation:
		return c.IncidentStatus.mutate(ctx, m)
	case *NotificationOutboxMutation:
		return c.NotificationOutbox.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ComponentClient is a client for the Component schema.
type ComponentClient struct {
	config
}

// NewComponentClient returns a client for the Component from the given config.
func NewComponentClient(c config) *ComponentClient {
	return &ComponentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `component.Hooks(f(g(h())))`.
func (c *ComponentClient) Use(hooks ...Hook) {
	c.hooks.Component = append(c.hooks.Component, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `component.Intercept(f(g(h())))`.
func (c *ComponentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Component = append(c.inters.Component, interceptors...)
}

// Create returns a builder for creating a Component entity.
func (c *ComponentClient) Create() *ComponentCreate {
	mutation := newComponentMutation(c.config, OpCreate)
	return &ComponentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Component entities.
func (c *ComponentClient) CreateBulk(builders ...*ComponentCreate) *ComponentCreateBulk {
	return &ComponentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ComponentClient) MapCreateBulk(slice any, setFunc func(*ComponentCreate, int)) *ComponentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ComponentCreateBulk{err: fmt.Errorf("calling to ComponentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ComponentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ComponentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Component.
func (c *ComponentClient) Update() *ComponentUpdate {
	mutation := newComponentMutation(c.config, OpUpdate)
	return &ComponentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ComponentClient) UpdateOne(_m *Component) *ComponentUpdateOne {
	mutation := newComponentMutation(c.config, OpUpdateOne, withComponent(_m))
	return &ComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ComponentClient) UpdateOneID(id int) *ComponentUpdateOne {
	mutation := newComponentMutation(c.config, OpUpdateOne, withComponentID(id))
	return &ComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Component.
func (c *ComponentClient) Delete() *ComponentDelete {
	mutation := newComponentMutation(c.config, OpDelete)
	return &ComponentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ComponentClient) DeleteOne(_m *Component) *ComponentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ComponentClient) DeleteOneID(id int) *ComponentDeleteOne {
	builder := c.Delete().Where(component.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ComponentDeleteOne{builder}
}

// Query returns a query builder for Component.
func (c *ComponentClient) Query() *ComponentQuery {
	return &ComponentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeComponent},
		inters: c.Interceptors(),
	}
}

// Get returns a Component entity by its id.
func (c *ComponentClient) Get(ctx context.Context, id int) (*Component, error) {
	return c.Query().Where(component.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ComponentClient) GetX(ctx context.Context, id int) *Component {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAttributes queries the attributes edge of a Component.
func (c *ComponentClient) QueryAttributes(_m *Component) *ComponentAttrQuery {
	query := (&ComponentAttrClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(component.Table, component.FieldID, id),
			sqlgraph.To(componentattr.Table, componentattr.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, component.AttributesTable, component.AttributesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIncidents queries the incidents edge of a Component.
func (c *ComponentClient) QueryIncidents(_m *Component) *IncidentQuery {
	query := (&IncidentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(component.Table, component.FieldID, id),
			sqlgraph.To(incident.Table, incident.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, component.IncidentsTable, component.IncidentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ComponentClient) Hooks() []Hook {
	return c.hooks.Component
}

// Interceptors returns the client interceptors.
func (c *ComponentClient) Interceptors() []Interceptor {
	return c.inters.Component
}

func (c *ComponentClient) mutate(ctx context.Context, m *ComponentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ComponentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ComponentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ComponentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ComponentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Component mutation op: %q", m.Op())
	}
}

// ComponentAttrClient is a client for the ComponentAttr schema.
type ComponentAttrClient struct {
	config
}

// NewComponentAttrClient returns a client for the ComponentAttr from the given config.
func NewComponentAttrClient(c config) *ComponentAttrClient {
	return &ComponentAttrClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `componentattr.Hooks(f(g(h())))`.
func (c *ComponentAttrClient) Use(hooks ...Hook) {
	c.hooks.ComponentAttr = append(c.hooks.ComponentAttr, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `componentattr.Intercept(f(g(h())))`.
func (c *ComponentAttrClient) Intercept(interceptors ...Interceptor) {
	c.inters.ComponentAttr = append(c.inters.ComponentAttr, interceptors...)
}

// Create returns a builder for creating a ComponentAttr entity.
func (c *ComponentAttrClient) Create() *ComponentAttrCreate {
	mutation := newComponentAttrMutation(c.config, OpCreate)
	return &ComponentAttrCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ComponentAttr entities.
func (c *ComponentAttrClient) CreateBulk(builders ...*ComponentAttrCreate) *ComponentAttrCreateBulk {
	return &ComponentAttrCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ComponentAttrClient) MapCreateBulk(slice any, setFunc func(*ComponentAttrCreate, int)) *ComponentAttrCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ComponentAttrCreateBulk{err: fmt.Errorf("calling to ComponentAttrClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ComponentAttrCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ComponentAttrCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ComponentAttr.
func (c *ComponentAttrClient) Update() *ComponentAttrUpdate {
	mutation := newComponentAttrMutation(c.config, OpUpdate)
	return &ComponentAttrUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ComponentAttrClient) UpdateOne(_m *ComponentAttr) *ComponentAttrUpdateOne {
	mutation := newComponentAttrMutation(c.config, OpUpdateOne, withComponentAttr(_m))
	return &ComponentAttrUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ComponentAttrClient) UpdateOneID(id int) *ComponentAttrUpdateOne {
	mutation := newComponentAttrMutation(c.config, OpUpdateOne, withComponentAttrID(id))
	return &ComponentAttrUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ComponentAttr.
func (c *ComponentAttrClient) Delete() *ComponentAttrDelete {
	mutation := newComponentAttrMutation(c.config, OpDelete)
	return &ComponentAttrDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ComponentAttrClient) DeleteOne(_m *ComponentAttr) *ComponentAttrDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ComponentAttrClient) DeleteOneID(id int) *ComponentAttrDeleteOne {
	builder := c.Delete().Where(componentattr.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ComponentAttrDeleteOne{builder}
}

// Query returns a query builder for ComponentAttr.
func (c *ComponentAttrClient) Query() *ComponentAttrQuery {
	return &ComponentAttrQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeComponentAttr},
		inters: c.Interceptors(),
	}
}

// Get returns a ComponentAttr entity by its id.
func (c *ComponentAttrClient) Get(ctx context.Context, id int) (*ComponentAttr, error) {
	return c.Query().Where(componentattr.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ComponentAttrClient) GetX(ctx context.Context, id int) *ComponentAttr {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryComponent queries the component edge of a ComponentAttr.
func (c *ComponentAttrClient) QueryComponent(_m *ComponentAttr) *ComponentQuery {
	query := (&ComponentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(componentattr.Table, componentattr.FieldID, id),
			sqlgraph.To(component.Table, component.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, componentattr.ComponentTable, componentattr.ComponentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ComponentAttrClient) Hooks() []Hook {
	return c.hooks.ComponentAttr
}

// Interceptors returns the client interceptors.
func (c *ComponentAttrClient) Interceptors() []Interceptor {
	return c.inters.ComponentAttr
}

func (c *ComponentAttrClient) mutate(ctx context.Context, m *ComponentAttrMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ComponentAttrCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ComponentAttrUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ComponentAttrUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ComponentAttrDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ComponentAttr mutation op: %q", m.Op())
	}
}

// IncidentClient is a client for the Incident schema.
type IncidentClient struct {
	config
}

// NewIncidentClient returns a client for the Incident from the given config.
func NewIncidentClient(c config) *IncidentClient {
	return &IncidentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `incident.Hooks(f(g(h())))`.
func (c *IncidentClient) Use(hooks ...Hook) {
	c.hooks.Incident = append(c.hooks.Incident, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `incident.Intercept(f(g(h())))`.
func (c *IncidentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Incident = append(c.inters.Incident, interceptors...)
}

// Create returns a builder for creating a Incident entity.
func (c *IncidentClient) Create() *IncidentCreate {
	mutation := newIncidentMutation(c.config, OpCreate)
	return &IncidentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Incident entities.
func (c *IncidentClient) CreateBulk(builders ...*IncidentCreate) *IncidentCreateBulk {
	return &IncidentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IncidentClient) MapCreateBulk(slice any, setFunc func(*IncidentCreate, int)) *IncidentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IncidentCreateBulk{err: fmt.Errorf("calling to IncidentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IncidentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IncidentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Incident.
func (c *IncidentClient) Update() *IncidentUpdate {
	mutation := newIncidentMutation(c.config, OpUpdate)
	return &IncidentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IncidentClient) UpdateOne(_m *Incident) *IncidentUpdateOne {
	mutation := newIncidentMutation(c.config, OpUpdateOne, withIncident(_m))
	return &IncidentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IncidentClient) UpdateOneID(id int) *IncidentUpdateOne {
	mutation := newIncidentMutation(c.config, OpUpdateOne, withIncidentID(id))
	return &IncidentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Incident.
func (c *IncidentClient) Delete() *IncidentDelete {
	mutation := newIncidentMutation(c.config, OpDelete)
	return &IncidentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IncidentClient) DeleteOne(_m *Incident) *IncidentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IncidentClient) DeleteOneID(id int) *IncidentDeleteOne {
	builder := c.Delete().Where(incident.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IncidentDeleteOne{builder}
}

// Query returns a query builder for Incident.
func (c *IncidentClient) Query() *IncidentQuery {
	return &IncidentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIncident},
		inters: c.Interceptors(),
	}
}

// Get returns a Incident entity by its id.
func (c *IncidentClient) Get(ctx context.Context, id int) (*Incident, error) {
	return c.Query().Where(incident.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IncidentClient) GetX(ctx context.Context, id int) *Incident {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryComponents queries the components edge of a Incident.
func (c *IncidentClient) QueryComponents(_m *Incident) *ComponentQuery {
	query := (&ComponentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, id),
			sqlgraph.To(component.Table, component.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, incident.ComponentsTable, incident.ComponentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryNotifications queries the notifications edge of a Incident.
func (c *IncidentClient) QueryNotifications(_m *Incident) *NotificationOutboxQuery {
	query := (&NotificationOutboxClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(incident.Table, incident.FieldID, id),
			sqlgraph.To(notificationoutbox.Table, notificationoutbox.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, incident.NotificationsTable, incident.NotificationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IncidentClient) Hooks() []Hook {
	return c.hooks.Incident
}

// Interceptors returns the client interceptors.
func (c *IncidentClient) Interceptors() []Interceptor {
	return c.inters.Incident
}

func (c *IncidentClient) mutate(ctx context.Context, m *IncidentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IncidentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IncidentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IncidentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IncidentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Incident mutation op: %q", m.Op())
	}
}

// IncidentStatusClient is a client for the IncidentStatus schema.
type IncidentStatusClient struct {
	config
}

// NewIncidentStatusClient returns a client for the IncidentStatus from the given config.
func NewIncidentStatusClient(c config) *IncidentStatusClient {
	return &IncidentStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `incidentstatus.Hooks(f(g(h())))`.
func (c *IncidentStatusClient) Use(hooks ...Hook) {
	c.hooks.IncidentStatus = append(c.hooks.IncidentStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `incidentstatus.Intercept(f(g(h())))`.
func (c *IncidentStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.IncidentStatus = append(c.inters.IncidentStatus, interceptors...)
}

// Create returns a builder for creating a IncidentStatus entity.
func (c *IncidentStatusClient) Create() *IncidentStatusCreate {
	mutation := newIncidentStatusMutation(c.config, OpCreate)
	return &IncidentStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IncidentStatus entities.
func (c *IncidentStatusClient) CreateBulk(builders ...*IncidentStatusCreate) *IncidentStatusCreateBulk {
	return &IncidentStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IncidentStatusClient) MapCreateBulk(slice any, setFunc func(*IncidentStatusCreate, int)) *IncidentStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IncidentStatusCreateBulk{err: fmt.Errorf("calling to IncidentStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IncidentStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IncidentStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IncidentStatus.
func (c *IncidentStatusClient) Update() *IncidentStatusUpdate {
	mutation := newIncidentStatusMutation(c.config, OpUpdate)
	return &IncidentStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IncidentStatusClient) UpdateOne(_m *IncidentStatus) *IncidentStatusUpdateOne {
	mutation := newIncidentStatusMutation(c.config, OpUpdateOne, withIncidentStatus(_m))
	return &IncidentStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IncidentStatusClient) UpdateOneID(id int) *IncidentStatusUpdateOne {
	mutation := newIncidentStatusMutation(c.config, OpUpdateOne, withIncidentStatusID(id))
	return &IncidentStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IncidentStatus.
func (c *IncidentStatusClient) Delete() *IncidentStatusDelete {
	mutation := newIncidentStatusMutation(c.config, OpDelete)
	return &IncidentStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IncidentStatusClient) DeleteOne(_m *IncidentStatus) *IncidentStatusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IncidentStatusClient) DeleteOneID(id int) *IncidentStatusDeleteOne {
	builder := c.Delete().Where(incidentstatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IncidentStatusDeleteOne{builder}
}

// Query returns a query builder for IncidentStatus.
func (c *IncidentStatusClient) Query() *IncidentStatusQuery {
	return &IncidentStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIncidentStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a IncidentStatus entity by its id.
func (c *IncidentStatusClient) Get(ctx context.Context, id int) (*IncidentStatus, error) {
	return c.Query().Where(incidentstatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IncidentStatusClient) GetX(ctx context.Context, id int) *IncidentStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IncidentStatusClient) Hooks() []Hook {
	return c.hooks.IncidentStatus
}

// Interceptors returns the client interceptors.
func (c *IncidentStatusClient) Interceptors() []Interceptor {
	return c.inters.IncidentStatus
}

func (c *IncidentStatusClient) mutate(ctx context.Context, m *IncidentStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IncidentStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IncidentStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IncidentStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IncidentStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IncidentStatus mutation op: %q", m.Op())
	}
}

// NotificationOutboxClient is a client for the NotificationOutbox schema.
type NotificationOutboxClient struct {
	config
}

// NewNotificationOutboxClient returns a client for the NotificationOutbox from the given config.
func NewNotificationOutboxClient(c config) *NotificationOutboxClient {
	return &NotificationOutboxClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notificationoutbox.Hooks(f(g(h())))`.
func (c *NotificationOutboxClient) Use(hooks ...Hook) {
	c.hooks.NotificationOutbox = append(c.hooks.NotificationOutbox, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notificationoutbox.Intercept(f(g(h())))`.
func (c *NotificationOutboxClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotificationOutbox = append(c.inters.NotificationOutbox, interceptors...)
}

// Create returns a builder for creating a NotificationOutbox entity.
func (c *NotificationOutboxClient) Create() *NotificationOutboxCreate {
	mutation := newNotificationOutboxMutation(c.config, OpCreate)
	return &NotificationOutboxCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotificationOutbox entities.
func (c *NotificationOutboxClient) CreateBulk(builders ...*NotificationOutboxCreate) *NotificationOutboxCreateBulk {
	return &NotificationOutboxCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationOutboxClient) MapCreateBulk(slice any, setFunc func(*NotificationOutboxCreate, int)) *NotificationOutboxCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationOutboxCreateBulk{err: fmt.Errorf("calling to NotificationOutboxClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationOutboxCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationOutboxCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotificationOutbox.
func (c *NotificationOutboxClient) Update() *NotificationOutboxUpdate {
	mutation := newNotificationOutboxMutation(c.config, OpUpdate)
	return &NotificationOutboxUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationOutboxClient) UpdateOne(_m *NotificationOutbox) *NotificationOutboxUpdateOne {
	mutation := newNotificationOutboxMutation(c.config, OpUpdateOne, withNotificationOutbox(_m))
	return &NotificationOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationOutboxClient) UpdateOneID(id int) *NotificationOutboxUpdateOne {
	mutation := newNotificationOutboxMutation(c.config, OpUpdateOne, withNotificationOutboxID(id))
	return &NotificationOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotificationOutbox.
func (c *NotificationOutboxClient) Delete() *NotificationOutboxDelete {
	mutation := newNotificationOutboxMutation(c.config, OpDelete)
	return &NotificationOutboxDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationOutboxClient) DeleteOne(_m *NotificationOutbox) *NotificationOutboxDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationOutboxClient) DeleteOneID(id int) *NotificationOutboxDeleteOne {
	builder := c.Delete().Where(notificationoutbox.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationOutboxDeleteOne{builder}
}

// Query returns a query builder for NotificationOutbox.
func (c *NotificationOutboxClient) Query() *NotificationOutboxQuery {
	return &NotificationOutboxQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotificationOutbox},
		inters: c.Interceptors(),
	}
}

// Get returns a NotificationOutbox entity by its id.
func (c *NotificationOutboxClient) Get(ctx context.Context, id int) (*NotificationOutbox, error) {
	return c.Query().Where(notificationoutbox.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationOutboxClient) GetX(ctx context.Context, id int) *NotificationOutbox {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIncident queries the incident edge of a NotificationOutbox.
func (c *NotificationOutboxClient) QueryIncident(_m *NotificationOutbox) *IncidentQuery {
	query := (&IncidentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(notificationoutbox.Table, notificationoutbox.FieldID, id),
			sqlgraph.To(incident.Table, incident.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, notificationoutbox.IncidentTable, notificationoutbox.IncidentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NotificationOutboxClient) Hooks() []Hook {
	return c.hooks.NotificationOutbox
}

// Interceptors returns the client interceptors.
func (c *NotificationOutboxClient) Interceptors() []Interceptor {
	return c.inters.NotificationOutbox
}

func (c *NotificationOutboxClient) mutate(ctx context.Context, m *NotificationOutboxMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationOutboxCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationOutboxUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationOutboxUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationOutboxDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotificationOutbox mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Component, ComponentAttr, Incident, IncidentStatus,
		NotificationOutbox []ent.Hook
	}
	inters struct {
		Component, ComponentAttr, Incident, IncidentStatus,
		NotificationOutbox []ent.Interceptor
	}
)
