// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/componentattr"
)

// ComponentAttr is the model entity for the ComponentAttr schema.
type ComponentAttr struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ComponentID holds the value of the "component_id" field.
	ComponentID int `json:"component_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ComponentAttrQuery when eager-loading is set.
	Edges        ComponentAttrEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ComponentAttrEdges holds the relations/edges for other nodes in the graph.
type ComponentAttrEdges struct {
	// Component holds the value of the component edge.
	Component *Component `json:"component,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ComponentOrErr returns the Component value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ComponentAttrEdges) ComponentOrErr() (*Component, error) {
	if e.Component != nil {
		return e.Component, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: component.Label}
	}
	return nil, &NotLoadedError{edge: "component"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ComponentAttr) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case componentattr.FieldID, componentattr.FieldComponentID:
			values[i] = new(sql.NullInt64)
		case componentattr.FieldName, componentattr.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ComponentAttr fields.
func (_m *ComponentAttr) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case componentattr.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case componentattr.FieldComponentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field component_id", values[i])
			} else if value.Valid {
				_m.ComponentID = int(value.Int64)
			}
		case componentattr.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case componentattr.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the ComponentAttr.
// This includes values selected through modifiers, order, etc.
func (_m *ComponentAttr) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryComponent queries the "component" edge of the ComponentAttr entity.
func (_m *ComponentAttr) QueryComponent() *ComponentQuery {
	return NewComponentAttrClient(_m.config).QueryComponent(_m)
}

// Update returns a builder for updating this ComponentAttr.
// Note that you need to call ComponentAttr.Unwrap() before calling this method if this ComponentAttr
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ComponentAttr) Update() *ComponentAttrUpdateOne {
	return NewComponentAttrClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ComponentAttr entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ComponentAttr) Unwrap() *ComponentAttr {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ComponentAttr is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ComponentAttr) String() string {
	var builder strings.Builder
	builder.WriteString("ComponentAttr(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("component_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ComponentID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// ComponentAttrs is a parsable slice of ComponentAttr.
type ComponentAttrs []*ComponentAttr
