// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/componentattr"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// ComponentAttrUpdate is the builder for updating ComponentAttr entities.
type ComponentAttrUpdate struct {
	config
	hooks    []Hook
	mutation *ComponentAttrMutation
}

// Where appends a list predicates to the ComponentAttrUpdate builder.
func (_u *ComponentAttrUpdate) Where(ps ...predicate.ComponentAttr) *ComponentAttrUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetComponentID sets the "component_id" field.
func (_u *ComponentAttrUpdate) SetComponentID(v int) *ComponentAttrUpdate {
	_u.mutation.SetComponentID(v)
	return _u
}

// SetNillableComponentID sets the "component_id" field if the given value is not nil.
func (_u *ComponentAttrUpdate) SetNillableComponentID(v *int) *ComponentAttrUpdate {
	if v != nil {
		_u.SetComponentID(*v)
	}
	return _u
}

// ClearComponentID clears the value of the "component_id" field.
func (_u *ComponentAttrUpdate) ClearComponentID() *ComponentAttrUpdate {
	_u.mutation.ClearComponentID()
	return _u
}

// SetName sets the "name" field.
func (_u *ComponentAttrUpdate) SetName(v string) *ComponentAttrUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ComponentAttrUpdate) SetNillableName(v *string) *ComponentAttrUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ComponentAttrUpdate) SetValue(v string) *ComponentAttrUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ComponentAttrUpdate) SetNillableValue(v *string) *ComponentAttrUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetComponent sets the "component" edge to the Component entity.
func (_u *ComponentAttrUpdate) SetComponent(v *Component) *ComponentAttrUpdate {
	return _u.SetComponentID(v.ID)
}

// Mutation returns the ComponentAttrMutation object of the builder.
func (_u *ComponentAttrUpdate) Mutation() *ComponentAttrMutation {
	return _u.mutation
}

// ClearComponent clears the "component" edge to the Component entity.
func (_u *ComponentAttrUpdate) ClearComponent() *ComponentAttrUpdate {
	_u.mutation.ClearComponent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ComponentAttrUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ComponentAttrUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ComponentAttrUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ComponentAttrUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ComponentAttrUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := componentattr.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := componentattr.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.value": %w`, err)}
		}
	}
	return nil
}

func (_u *ComponentAttrUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(componentattr.Table, componentattr.Columns, sqlgraph.NewFieldSpec(componentattr.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(componentattr.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(componentattr.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   componentattr.ComponentTable,
			Columns: []string{componentattr.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   componentattr.ComponentTable,
			Columns: []string{componentattr.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{componentattr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ComponentAttrUpdateOne is the builder for updating a single ComponentAttr entity.
type ComponentAttrUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ComponentAttrMutation
}

// SetComponentID sets the "component_id" field.
func (_u *ComponentAttrUpdateOne) SetComponentID(v int) *ComponentAttrUpdateOne {
	_u.mutation.SetComponentID(v)
	return _u
}

// SetNillableComponentID sets the "component_id" field if the given value is not nil.
func (_u *ComponentAttrUpdateOne) SetNillableComponentID(v *int) *ComponentAttrUpdateOne {
	if v != nil {
		_u.SetComponentID(*v)
	}
	return _u
}

// ClearComponentID clears the value of the "component_id" field.
func (_u *ComponentAttrUpdateOne) ClearComponentID() *ComponentAttrUpdateOne {
	_u.mutation.ClearComponentID()
	return _u
}

// SetName sets the "name" field.
func (_u *ComponentAttrUpdateOne) SetName(v string) *ComponentAttrUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ComponentAttrUpdateOne) SetNillableName(v *string) *ComponentAttrUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ComponentAttrUpdateOne) SetValue(v string) *ComponentAttrUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ComponentAttrUpdateOne) SetNillableValue(v *string) *ComponentAttrUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetComponent sets the "component" edge to the Component entity.
func (_u *ComponentAttrUpdateOne) SetComponent(v *Component) *ComponentAttrUpdateOne {
	return _u.SetComponentID(v.ID)
}

// Mutation returns the ComponentAttrMutation object of the builder.
func (_u *ComponentAttrUpdateOne) Mutation() *ComponentAttrMutation {
	return _u.mutation
}

// ClearComponent clears the "component" edge to the Component entity.
func (_u *ComponentAttrUpdateOne) ClearComponent() *ComponentAttrUpdateOne {
	_u.mutation.ClearComponent()
	return _u
}

// Where appends a list predicates to the ComponentAttrUpdate builder.
func (_u *ComponentAttrUpdateOne) Where(ps ...predicate.ComponentAttr) *ComponentAttrUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ComponentAttrUpdateOne) Select(field string, fields ...string) *ComponentAttrUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ComponentAttr entity.
func (_u *ComponentAttrUpdateOne) Save(ctx context.Context) (*ComponentAttr, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ComponentAttrUpdateOne) SaveX(ctx context.Context) *ComponentAttr {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ComponentAttrUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ComponentAttrUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ComponentAttrUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := componentattr.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := componentattr.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.value": %w`, err)}
		}
	}
	return nil
}

func (_u *ComponentAttrUpdateOne) sqlSave(ctx context.Context) (_node *ComponentAttr, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(componentattr.Table, componentattr.Columns, sqlgraph.NewFieldSpec(componentattr.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ComponentAttr.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, componentattr.FieldID)
		for _, f := range fields {
			if !componentattr.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != componentattr.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(componentattr.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(componentattr.FieldValue, field.TypeString, value)
	}
	if _u.mutation.ComponentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   componentattr.ComponentTable,
			Columns: []string{componentattr.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   componentattr.ComponentTable,
			Columns: []string{componentattr.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ComponentAttr{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{componentattr.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
