// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/componentattr"
)

// ComponentAttrCreate is the builder for creating a ComponentAttr entity.
type ComponentAttrCreate struct {
	config
	mutation *ComponentAttrMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetComponentID sets the "component_id" field.
func (_c *ComponentAttrCreate) SetComponentID(v int) *ComponentAttrCreate {
	_c.mutation.SetComponentID(v)
	return _c
}

// SetNillableComponentID sets the "component_id" field if the given value is not nil.
func (_c *ComponentAttrCreate) SetNillableComponentID(v *int) *ComponentAttrCreate {
	if v != nil {
		_c.SetComponentID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ComponentAttrCreate) SetName(v string) *ComponentAttrCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ComponentAttrCreate) SetValue(v string) *ComponentAttrCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ComponentAttrCreate) SetID(v int) *ComponentAttrCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetComponent sets the "component" edge to the Component entity.
func (_c *ComponentAttrCreate) SetComponent(v *Component) *ComponentAttrCreate {
	return _c.SetComponentID(v.ID)
}

// Mutation returns the ComponentAttrMutation object of the builder.
func (_c *ComponentAttrCreate) Mutation() *ComponentAttrMutation {
	return _c.mutation
}

// Save creates the ComponentAttr in the database.
func (_c *ComponentAttrCreate) Save(ctx context.Context) (*ComponentAttr, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ComponentAttrCreate) SaveX(ctx context.Context) *ComponentAttr {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentAttrCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentAttrCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ComponentAttrCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ComponentAttr.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := componentattr.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ComponentAttr.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := componentattr.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "ComponentAttr.value": %w`, err)}
		}
	}
	return nil
}

func (_c *ComponentAttrCreate) sqlSave(ctx context.Context) (*ComponentAttr, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ComponentAttrCreate) createSpec() (*ComponentAttr, *sqlgraph.CreateSpec) {
	var (
		_node = &ComponentAttr{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(componentattr.Table, sqlgraph.NewFieldSpec(componentattr.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(componentattr.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(componentattr.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := _c.mutation.ComponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   componentattr.ComponentTable,
			Columns: []string{componentattr.ComponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ComponentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ComponentAttr.Create().
//		SetComponentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComponentAttrUpsert) {
//			SetComponentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComponentAttrCreate) OnConflict(opts ...sql.ConflictOption) *ComponentAttrUpsertOne {
	_c.conflict = opts
	return &ComponentAttrUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComponentAttrCreate) OnConflictColumns(columns ...string) *ComponentAttrUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComponentAttrUpsertOne{
		create: _c,
	}
}

type (
	// ComponentAttrUpsertOne is the builder for "upsert"-ing
	//  one ComponentAttr node.
	ComponentAttrUpsertOne struct {
		create *ComponentAttrCreate
	}

	// ComponentAttrUpsert is the "OnConflict" setter.
	ComponentAttrUpsert struct {
		*sql.UpdateSet
	}
)

// SetComponentID sets the "component_id" field.
func (u *ComponentAttrUpsert) SetComponentID(v int) *ComponentAttrUpsert {
	u.Set(componentattr.FieldComponentID, v)
	return u
}

// UpdateComponentID sets the "component_id" field to the value that was provided on create.
func (u *ComponentAttrUpsert) UpdateComponentID() *ComponentAttrUpsert {
	u.SetExcluded(componentattr.FieldComponentID)
	return u
}

// ClearComponentID clears the value of the "component_id" field.
func (u *ComponentAttrUpsert) ClearComponentID() *ComponentAttrUpsert {
	u.SetNull(componentattr.FieldComponentID)
	return u
}

// SetName sets the "name" field.
func (u *ComponentAttrUpsert) SetName(v string) *ComponentAttrUpsert {
	u.Set(componentattr.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentAttrUpsert) UpdateName() *ComponentAttrUpsert {
	u.SetExcluded(componentattr.FieldName)
	return u
}

// SetValue sets the "value" field.
func (u *ComponentAttrUpsert) SetValue(v string) *ComponentAttrUpsert {
	u.Set(componentattr.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ComponentAttrUpsert) UpdateValue() *ComponentAttrUpsert {
	u.SetExcluded(componentattr.FieldValue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(componentattr.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComponentAttrUpsertOne) UpdateNewValues() *ComponentAttrUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(componentattr.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ComponentAttrUpsertOne) Ignore() *ComponentAttrUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComponentAttrUpsertOne) DoNothing() *ComponentAttrUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComponentAttrCreate.OnConflict
// documentation for more info.
func (u *ComponentAttrUpsertOne) Update(set func(*ComponentAttrUpsert)) *ComponentAttrUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComponentAttrUpsert{UpdateSet: update})
	}))
	return u
}

// SetComponentID sets the "component_id" field.
func (u *ComponentAttrUpsertOne) SetComponentID(v int) *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetComponentID(v)
	})
}

// UpdateComponentID sets the "component_id" field to the value that was provided on create.
func (u *ComponentAttrUpsertOne) UpdateComponentID() *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateComponentID()
	})
}

// ClearComponentID clears the value of the "component_id" field.
func (u *ComponentAttrUpsertOne) ClearComponentID() *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.ClearComponentID()
	})
}

// SetName sets the "name" field.
func (u *ComponentAttrUpsertOne) SetName(v string) *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentAttrUpsertOne) UpdateName() *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateName()
	})
}

// SetValue sets the "value" field.
func (u *ComponentAttrUpsertOne) SetValue(v string) *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ComponentAttrUpsertOne) UpdateValue() *ComponentAttrUpsertOne {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *ComponentAttrUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComponentAttrCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComponentAttrUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ComponentAttrUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ComponentAttrUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ComponentAttrCreateBulk is the builder for creating many ComponentAttr entities in bulk.
type ComponentAttrCreateBulk struct {
	config
	err      error
	builders []*ComponentAttrCreate
	conflict []sql.ConflictOption
}

// Save creates the ComponentAttr entities in the database.
func (_c *ComponentAttrCreateBulk) Save(ctx context.Context) ([]*ComponentAttr, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ComponentAttr, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComponentAttrMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ComponentAttrCreateBulk) SaveX(ctx context.Context) []*ComponentAttr {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentAttrCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentAttrCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ComponentAttr.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComponentAttrUpsert) {
//			SetComponentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComponentAttrCreateBulk) OnConflict(opts ...sql.ConflictOption) *ComponentAttrUpsertBulk {
	_c.conflict = opts
	return &ComponentAttrUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComponentAttrCreateBulk) OnConflictColumns(columns ...string) *ComponentAttrUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComponentAttrUpsertBulk{
		create: _c,
	}
}

// ComponentAttrUpsertBulk is the builder for "upsert"-ing
// a bulk of ComponentAttr nodes.
type ComponentAttrUpsertBulk struct {
	create *ComponentAttrCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(componentattr.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComponentAttrUpsertBulk) UpdateNewValues() *ComponentAttrUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(componentattr.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ComponentAttr.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ComponentAttrUpsertBulk) Ignore() *ComponentAttrUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComponentAttrUpsertBulk) DoNothing() *ComponentAttrUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComponentAttrCreateBulk.OnConflict
// documentation for more info.
func (u *ComponentAttrUpsertBulk) Update(set func(*ComponentAttrUpsert)) *ComponentAttrUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComponentAttrUpsert{UpdateSet: update})
	}))
	return u
}

// SetComponentID sets the "component_id" field.
func (u *ComponentAttrUpsertBulk) SetComponentID(v int) *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetComponentID(v)
	})
}

// UpdateComponentID sets the "component_id" field to the value that was provided on create.
func (u *ComponentAttrUpsertBulk) UpdateComponentID() *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateComponentID()
	})
}

// ClearComponentID clears the value of the "component_id" field.
func (u *ComponentAttrUpsertBulk) ClearComponentID() *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.ClearComponentID()
	})
}

// SetName sets the "name" field.
func (u *ComponentAttrUpsertBulk) SetName(v string) *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ComponentAttrUpsertBulk) UpdateName() *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateName()
	})
}

// SetValue sets the "value" field.
func (u *ComponentAttrUpsertBulk) SetValue(v string) *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *ComponentAttrUpsertBulk) UpdateValue() *ComponentAttrUpsertBulk {
	return u.Update(func(s *ComponentAttrUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *ComponentAttrUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ComponentAttrCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComponentAttrCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComponentAttrUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
