// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/incidentstatus"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// IncidentStatusUpdate is the builder for updating IncidentStatus entities.
type IncidentStatusUpdate struct {
	config
	hooks    []Hook
	mutation *IncidentStatusMutation
}

// Where appends a list predicates to the IncidentStatusUpdate builder.
func (_u *IncidentStatusUpdate) Where(ps ...predicate.IncidentStatus) *IncidentStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *IncidentStatusUpdate) SetIncidentID(v int) *IncidentStatusUpdate {
	_u.mutation.ResetIncidentID()
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableIncidentID(v *int) *IncidentStatusUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// AddIncidentID adds value to the "incident_id" field.
func (_u *IncidentStatusUpdate) AddIncidentID(v int) *IncidentStatusUpdate {
	_u.mutation.AddIncidentID(v)
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *IncidentStatusUpdate) ClearIncidentID() *IncidentStatusUpdate {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *IncidentStatusUpdate) SetTimestamp(v time.Time) *IncidentStatusUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableTimestamp(v *time.Time) *IncidentStatusUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *IncidentStatusUpdate) SetText(v string) *IncidentStatusUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableText(v *string) *IncidentStatusUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IncidentStatusUpdate) SetStatus(v string) *IncidentStatusUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableStatus(v *string) *IncidentStatusUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IncidentStatusUpdate) SetCreatedAt(v time.Time) *IncidentStatusUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableCreatedAt(v *time.Time) *IncidentStatusUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IncidentStatusUpdate) ClearCreatedAt() *IncidentStatusUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *IncidentStatusUpdate) SetModifiedAt(v time.Time) *IncidentStatusUpdate {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableModifiedAt(v *time.Time) *IncidentStatusUpdate {
	if v != nil {
		_u.SetModifiedAt(*v)
	}
	return _u
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (_u *IncidentStatusUpdate) ClearModifiedAt() *IncidentStatusUpdate {
	_u.mutation.ClearModifiedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IncidentStatusUpdate) SetDeletedAt(v time.Time) *IncidentStatusUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableDeletedAt(v *time.Time) *IncidentStatusUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IncidentStatusUpdate) ClearDeletedAt() *IncidentStatusUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IncidentStatusUpdate) SetCreatedBy(v string) *IncidentStatusUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableCreatedBy(v *string) *IncidentStatusUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *IncidentStatusUpdate) ClearCreatedBy() *IncidentStatusUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetModifiedBy sets the "modified_by" field.
func (_u *IncidentStatusUpdate) SetModifiedBy(v string) *IncidentStatusUpdate {
	_u.mutation.SetModifiedBy(v)
	return _u
}

// SetNillableModifiedBy sets the "modified_by" field if the given value is not nil.
func (_u *IncidentStatusUpdate) SetNillableModifiedBy(v *string) *IncidentStatusUpdate {
	if v != nil {
		_u.SetModifiedBy(*v)
	}
	return _u
}

// ClearModifiedBy clears the value of the "modified_by" field.
func (_u *IncidentStatusUpdate) ClearModifiedBy() *IncidentStatusUpdate {
	_u.mutation.ClearModifiedBy()
	return _u
}

// Mutation returns the IncidentStatusMutation object of the builder.
func (_u *IncidentStatusUpdate) Mutation() *IncidentStatusMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IncidentStatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IncidentStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IncidentStatusUpdate) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := incidentstatus.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := incidentstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IncidentStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(incidentstatus.Table, incidentstatus.Columns, sqlgraph.NewFieldSpec(incidentstatus.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(incidentstatus.FieldIncidentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIncidentID(); ok {
		_spec.AddField(incidentstatus.FieldIncidentID, field.TypeInt, value)
	}
	if _u.mutation.IncidentIDCleared() {
		_spec.ClearField(incidentstatus.FieldIncidentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(incidentstatus.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(incidentstatus.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(incidentstatus.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(incidentstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(incidentstatus.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(incidentstatus.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ModifiedAtCleared() {
		_spec.ClearField(incidentstatus.FieldModifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(incidentstatus.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(incidentstatus.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(incidentstatus.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(incidentstatus.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ModifiedBy(); ok {
		_spec.SetField(incidentstatus.FieldModifiedBy, field.TypeString, value)
	}
	if _u.mutation.ModifiedByCleared() {
		_spec.ClearField(incidentstatus.FieldModifiedBy, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incidentstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IncidentStatusUpdateOne is the builder for updating a single IncidentStatus entity.
type IncidentStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IncidentStatusMutation
}

// SetIncidentID sets the "incident_id" field.
func (_u *IncidentStatusUpdateOne) SetIncidentID(v int) *IncidentStatusUpdateOne {
	_u.mutation.ResetIncidentID()
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableIncidentID(v *int) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// AddIncidentID adds value to the "incident_id" field.
func (_u *IncidentStatusUpdateOne) AddIncidentID(v int) *IncidentStatusUpdateOne {
	_u.mutation.AddIncidentID(v)
	return _u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (_u *IncidentStatusUpdateOne) ClearIncidentID() *IncidentStatusUpdateOne {
	_u.mutation.ClearIncidentID()
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *IncidentStatusUpdateOne) SetTimestamp(v time.Time) *IncidentStatusUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableTimestamp(v *time.Time) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *IncidentStatusUpdateOne) SetText(v string) *IncidentStatusUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableText(v *string) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IncidentStatusUpdateOne) SetStatus(v string) *IncidentStatusUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableStatus(v *string) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IncidentStatusUpdateOne) SetCreatedAt(v time.Time) *IncidentStatusUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableCreatedAt(v *time.Time) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IncidentStatusUpdateOne) ClearCreatedAt() *IncidentStatusUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetModifiedAt sets the "modified_at" field.
func (_u *IncidentStatusUpdateOne) SetModifiedAt(v time.Time) *IncidentStatusUpdateOne {
	_u.mutation.SetModifiedAt(v)
	return _u
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableModifiedAt(v *time.Time) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetModifiedAt(*v)
	}
	return _u
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (_u *IncidentStatusUpdateOne) ClearModifiedAt() *IncidentStatusUpdateOne {
	_u.mutation.ClearModifiedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *IncidentStatusUpdateOne) SetDeletedAt(v time.Time) *IncidentStatusUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableDeletedAt(v *time.Time) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *IncidentStatusUpdateOne) ClearDeletedAt() *IncidentStatusUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IncidentStatusUpdateOne) SetCreatedBy(v string) *IncidentStatusUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableCreatedBy(v *string) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *IncidentStatusUpdateOne) ClearCreatedBy() *IncidentStatusUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetModifiedBy sets the "modified_by" field.
func (_u *IncidentStatusUpdateOne) SetModifiedBy(v string) *IncidentStatusUpdateOne {
	_u.mutation.SetModifiedBy(v)
	return _u
}

// SetNillableModifiedBy sets the "modified_by" field if the given value is not nil.
func (_u *IncidentStatusUpdateOne) SetNillableModifiedBy(v *string) *IncidentStatusUpdateOne {
	if v != nil {
		_u.SetModifiedBy(*v)
	}
	return _u
}

// ClearModifiedBy clears the value of the "modified_by" field.
func (_u *IncidentStatusUpdateOne) ClearModifiedBy() *IncidentStatusUpdateOne {
	_u.mutation.ClearModifiedBy()
	return _u
}

// Mutation returns the IncidentStatusMutation object of the builder.
func (_u *IncidentStatusUpdateOne) Mutation() *IncidentStatusMutation {
	return _u.mutation
}

// Where appends a list predicates to the IncidentStatusUpdate builder.
func (_u *IncidentStatusUpdateOne) Where(ps ...predicate.IncidentStatus) *IncidentStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IncidentStatusUpdateOne) Select(field string, fields ...string) *IncidentStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IncidentStatus entity.
func (_u *IncidentStatusUpdateOne) Save(ctx context.Context) (*IncidentStatus, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentStatusUpdateOne) SaveX(ctx context.Context) *IncidentStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IncidentStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IncidentStatusUpdateOne) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := incidentstatus.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := incidentstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IncidentStatusUpdateOne) sqlSave(ctx context.Context) (_node *IncidentStatus, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(incidentstatus.Table, incidentstatus.Columns, sqlgraph.NewFieldSpec(incidentstatus.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IncidentStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incidentstatus.FieldID)
		for _, f := range fields {
			if !incidentstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != incidentstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IncidentID(); ok {
		_spec.SetField(incidentstatus.FieldIncidentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIncidentID(); ok {
		_spec.AddField(incidentstatus.FieldIncidentID, field.TypeInt, value)
	}
	if _u.mutation.IncidentIDCleared() {
		_spec.ClearField(incidentstatus.FieldIncidentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(incidentstatus.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(incidentstatus.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(incidentstatus.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(incidentstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(incidentstatus.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModifiedAt(); ok {
		_spec.SetField(incidentstatus.FieldModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ModifiedAtCleared() {
		_spec.ClearField(incidentstatus.FieldModifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(incidentstatus.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(incidentstatus.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(incidentstatus.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(incidentstatus.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.ModifiedBy(); ok {
		_spec.SetField(incidentstatus.FieldModifiedBy, field.TypeString, value)
	}
	if _u.mutation.ModifiedByCleared() {
		_spec.ClearField(incidentstatus.FieldModifiedBy, field.TypeString)
	}
	_node = &IncidentStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incidentstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
