// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/incidentstatus"
)

// IncidentStatusCreate is the builder for creating a IncidentStatus entity.
type IncidentStatusCreate struct {
	config
	mutation *IncidentStatusMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIncidentID sets the "incident_id" field.
func (_c *IncidentStatusCreate) SetIncidentID(v int) *IncidentStatusCreate {
	_c.mutation.SetIncidentID(v)
	return _c
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableIncidentID(v *int) *IncidentStatusCreate {
	if v != nil {
		_c.SetIncidentID(*v)
	}
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *IncidentStatusCreate) SetTimestamp(v time.Time) *IncidentStatusCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetText sets the "text" field.
func (_c *IncidentStatusCreate) SetText(v string) *IncidentStatusCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IncidentStatusCreate) SetStatus(v string) *IncidentStatusCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IncidentStatusCreate) SetCreatedAt(v time.Time) *IncidentStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableCreatedAt(v *time.Time) *IncidentStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *IncidentStatusCreate) SetModifiedAt(v time.Time) *IncidentStatusCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableModifiedAt(v *time.Time) *IncidentStatusCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IncidentStatusCreate) SetDeletedAt(v time.Time) *IncidentStatusCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableDeletedAt(v *time.Time) *IncidentStatusCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *IncidentStatusCreate) SetCreatedBy(v string) *IncidentStatusCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableCreatedBy(v *string) *IncidentStatusCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetModifiedBy sets the "modified_by" field.
func (_c *IncidentStatusCreate) SetModifiedBy(v string) *IncidentStatusCreate {
	_c.mutation.SetModifiedBy(v)
	return _c
}

// SetNillableModifiedBy sets the "modified_by" field if the given value is not nil.
func (_c *IncidentStatusCreate) SetNillableModifiedBy(v *string) *IncidentStatusCreate {
	if v != nil {
		_c.SetModifiedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IncidentStatusCreate) SetID(v int) *IncidentStatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IncidentStatusMutation object of the builder.
func (_c *IncidentStatusCreate) Mutation() *IncidentStatusMutation {
	return _c.mutation
}

// Save creates the IncidentStatus in the database.
func (_c *IncidentStatusCreate) Save(ctx context.Context) (*IncidentStatus, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IncidentStatusCreate) SaveX(ctx context.Context) *IncidentStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IncidentStatusCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "IncidentStatus.timestamp"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "IncidentStatus.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := incidentstatus.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IncidentStatus.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := incidentstatus.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IncidentStatus.status": %w`, err)}
		}
	}
	return nil
}

func (_c *IncidentStatusCreate) sqlSave(ctx context.Context) (*IncidentStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IncidentStatusCreate) createSpec() (*IncidentStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &IncidentStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(incidentstatus.Table, sqlgraph.NewFieldSpec(incidentstatus.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IncidentID(); ok {
		_spec.SetField(incidentstatus.FieldIncidentID, field.TypeInt, value)
		_node.IncidentID = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(incidentstatus.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(incidentstatus.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(incidentstatus.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(incidentstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(incidentstatus.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(incidentstatus.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(incidentstatus.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ModifiedBy(); ok {
		_spec.SetField(incidentstatus.FieldModifiedBy, field.TypeString, value)
		_node.ModifiedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IncidentStatus.Create().
//		SetIncidentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentStatusUpsert) {
//			SetIncidentID(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentStatusCreate) OnConflict(opts ...sql.ConflictOption) *IncidentStatusUpsertOne {
	_c.conflict = opts
	return &IncidentStatusUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentStatusCreate) OnConflictColumns(columns ...string) *IncidentStatusUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentStatusUpsertOne{
		create: _c,
	}
}

type (
	// IncidentStatusUpsertOne is the builder for "upsert"-ing
	//  one IncidentStatus node.
	IncidentStatusUpsertOne struct {
		create *IncidentStatusCreate
	}

	// IncidentStatusUpsert is the "OnConflict" setter.
	IncidentStatusUpsert struct {
		*sql.UpdateSet
	}
)

// SetIncidentID sets the "incident_id" field.
func (u *IncidentStatusUpsert) SetIncidentID(v int) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldIncidentID, v)
	return u
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateIncidentID() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldIncidentID)
	return u
}

// AddIncidentID adds v to the "incident_id" field.
func (u *IncidentStatusUpsert) AddIncidentID(v int) *IncidentStatusUpsert {
	u.Add(incidentstatus.FieldIncidentID, v)
	return u
}

// ClearIncidentID clears the value of the "incident_id" field.
func (u *IncidentStatusUpsert) ClearIncidentID() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldIncidentID)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *IncidentStatusUpsert) SetTimestamp(v time.Time) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateTimestamp() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldTimestamp)
	return u
}

// SetText sets the "text" field.
func (u *IncidentStatusUpsert) SetText(v string) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateText() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldText)
	return u
}

// SetStatus sets the "status" field.
func (u *IncidentStatusUpsert) SetStatus(v string) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateStatus() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldStatus)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentStatusUpsert) SetCreatedAt(v time.Time) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateCreatedAt() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentStatusUpsert) ClearCreatedAt() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldCreatedAt)
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentStatusUpsert) SetModifiedAt(v time.Time) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateModifiedAt() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldModifiedAt)
	return u
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentStatusUpsert) ClearModifiedAt() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldModifiedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentStatusUpsert) SetDeletedAt(v time.Time) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateDeletedAt() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentStatusUpsert) ClearDeletedAt() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentStatusUpsert) SetCreatedBy(v string) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateCreatedBy() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentStatusUpsert) ClearCreatedBy() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldCreatedBy)
	return u
}

// SetModifiedBy sets the "modified_by" field.
func (u *IncidentStatusUpsert) SetModifiedBy(v string) *IncidentStatusUpsert {
	u.Set(incidentstatus.FieldModifiedBy, v)
	return u
}

// UpdateModifiedBy sets the "modified_by" field to the value that was provided on create.
func (u *IncidentStatusUpsert) UpdateModifiedBy() *IncidentStatusUpsert {
	u.SetExcluded(incidentstatus.FieldModifiedBy)
	return u
}

// ClearModifiedBy clears the value of the "modified_by" field.
func (u *IncidentStatusUpsert) ClearModifiedBy() *IncidentStatusUpsert {
	u.SetNull(incidentstatus.FieldModifiedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(incidentstatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IncidentStatusUpsertOne) UpdateNewValues() *IncidentStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(incidentstatus.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IncidentStatusUpsertOne) Ignore() *IncidentStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentStatusUpsertOne) DoNothing() *IncidentStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentStatusCreate.OnConflict
// documentation for more info.
func (u *IncidentStatusUpsertOne) Update(set func(*IncidentStatusUpsert)) *IncidentStatusUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetIncidentID sets the "incident_id" field.
func (u *IncidentStatusUpsertOne) SetIncidentID(v int) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetIncidentID(v)
	})
}

// AddIncidentID adds v to the "incident_id" field.
func (u *IncidentStatusUpsertOne) AddIncidentID(v int) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.AddIncidentID(v)
	})
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateIncidentID() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateIncidentID()
	})
}

// ClearIncidentID clears the value of the "incident_id" field.
func (u *IncidentStatusUpsertOne) ClearIncidentID() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearIncidentID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *IncidentStatusUpsertOne) SetTimestamp(v time.Time) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateTimestamp() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateTimestamp()
	})
}

// SetText sets the "text" field.
func (u *IncidentStatusUpsertOne) SetText(v string) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateText() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateText()
	})
}

// SetStatus sets the "status" field.
func (u *IncidentStatusUpsertOne) SetStatus(v string) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateStatus() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentStatusUpsertOne) SetCreatedAt(v time.Time) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateCreatedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentStatusUpsertOne) ClearCreatedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentStatusUpsertOne) SetModifiedAt(v time.Time) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateModifiedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentStatusUpsertOne) ClearModifiedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentStatusUpsertOne) SetDeletedAt(v time.Time) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateDeletedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentStatusUpsertOne) ClearDeletedAt() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentStatusUpsertOne) SetCreatedBy(v string) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateCreatedBy() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentStatusUpsertOne) ClearCreatedBy() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearCreatedBy()
	})
}

// SetModifiedBy sets the "modified_by" field.
func (u *IncidentStatusUpsertOne) SetModifiedBy(v string) *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetModifiedBy(v)
	})
}

// UpdateModifiedBy sets the "modified_by" field to the value that was provided on create.
func (u *IncidentStatusUpsertOne) UpdateModifiedBy() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateModifiedBy()
	})
}

// ClearModifiedBy clears the value of the "modified_by" field.
func (u *IncidentStatusUpsertOne) ClearModifiedBy() *IncidentStatusUpsertOne {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearModifiedBy()
	})
}

// Exec executes the query.
func (u *IncidentStatusUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentStatusCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentStatusUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IncidentStatusUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IncidentStatusUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IncidentStatusCreateBulk is the builder for creating many IncidentStatus entities in bulk.
type IncidentStatusCreateBulk struct {
	config
	err      error
	builders []*IncidentStatusCreate
	conflict []sql.ConflictOption
}

// Save creates the IncidentStatus entities in the database.
func (_c *IncidentStatusCreateBulk) Save(ctx context.Context) ([]*IncidentStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IncidentStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncidentStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IncidentStatusCreateBulk) SaveX(ctx context.Context) []*IncidentStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IncidentStatus.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentStatusUpsert) {
//			SetIncidentID(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentStatusCreateBulk) OnConflict(opts ...sql.ConflictOption) *IncidentStatusUpsertBulk {
	_c.conflict = opts
	return &IncidentStatusUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentStatusCreateBulk) OnConflictColumns(columns ...string) *IncidentStatusUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentStatusUpsertBulk{
		create: _c,
	}
}

// IncidentStatusUpsertBulk is the builder for "upsert"-ing
// a bulk of IncidentStatus nodes.
type IncidentStatusUpsertBulk struct {
	create *IncidentStatusCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(incidentstatus.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IncidentStatusUpsertBulk) UpdateNewValues() *IncidentStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(incidentstatus.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IncidentStatus.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IncidentStatusUpsertBulk) Ignore() *IncidentStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentStatusUpsertBulk) DoNothing() *IncidentStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentStatusCreateBulk.OnConflict
// documentation for more info.
func (u *IncidentStatusUpsertBulk) Update(set func(*IncidentStatusUpsert)) *IncidentStatusUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentStatusUpsert{UpdateSet: update})
	}))
	return u
}

// SetIncidentID sets the "incident_id" field.
func (u *IncidentStatusUpsertBulk) SetIncidentID(v int) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetIncidentID(v)
	})
}

// AddIncidentID adds v to the "incident_id" field.
func (u *IncidentStatusUpsertBulk) AddIncidentID(v int) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.AddIncidentID(v)
	})
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateIncidentID() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateIncidentID()
	})
}

// ClearIncidentID clears the value of the "incident_id" field.
func (u *IncidentStatusUpsertBulk) ClearIncidentID() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearIncidentID()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *IncidentStatusUpsertBulk) SetTimestamp(v time.Time) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateTimestamp() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateTimestamp()
	})
}

// SetText sets the "text" field.
func (u *IncidentStatusUpsertBulk) SetText(v string) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateText() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateText()
	})
}

// SetStatus sets the "status" field.
func (u *IncidentStatusUpsertBulk) SetStatus(v string) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateStatus() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentStatusUpsertBulk) SetCreatedAt(v time.Time) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateCreatedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentStatusUpsertBulk) ClearCreatedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentStatusUpsertBulk) SetModifiedAt(v time.Time) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateModifiedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentStatusUpsertBulk) ClearModifiedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentStatusUpsertBulk) SetDeletedAt(v time.Time) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateDeletedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentStatusUpsertBulk) ClearDeletedAt() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentStatusUpsertBulk) SetCreatedBy(v string) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateCreatedBy() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentStatusUpsertBulk) ClearCreatedBy() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearCreatedBy()
	})
}

// SetModifiedBy sets the "modified_by" field.
func (u *IncidentStatusUpsertBulk) SetModifiedBy(v string) *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.SetModifiedBy(v)
	})
}

// UpdateModifiedBy sets the "modified_by" field to the value that was provided on create.
func (u *IncidentStatusUpsertBulk) UpdateModifiedBy() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.UpdateModifiedBy()
	})
}

// ClearModifiedBy clears the value of the "modified_by" field.
func (u *IncidentStatusUpsertBulk) ClearModifiedBy() *IncidentStatusUpsertBulk {
	return u.Update(func(s *IncidentStatusUpsert) {
		s.ClearModifiedBy()
	})
}

// Exec executes the query.
func (u *IncidentStatusUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IncidentStatusCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentStatusCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentStatusUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
