// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/incidentstatus"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// IncidentStatusDelete is the builder for deleting a IncidentStatus entity.
type IncidentStatusDelete struct {
	config
	hooks    []Hook
	mutation *IncidentStatusMutation
}

// Where appends a list predicates to the IncidentStatusDelete builder.
func (_d *IncidentStatusDelete) Where(ps ...predicate.IncidentStatus) *IncidentStatusDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IncidentStatusDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IncidentStatusDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IncidentStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(incidentstatus.Table, sqlgraph.NewFieldSpec(incidentstatus.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IncidentStatusDeleteOne is the builder for deleting a single IncidentStatus entity.
type IncidentStatusDeleteOne struct {
	_d *IncidentStatusDelete
}

// Where appends a list predicates to the IncidentStatusDelete builder.
func (_d *IncidentStatusDeleteOne) Where(ps ...predicate.IncidentStatus) *IncidentStatusDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IncidentStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{incidentstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IncidentStatusDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
