// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
)

// IncidentCreate is the builder for creating a Incident entity.
type IncidentCreate struct {
	config
	mutation *IncidentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetText sets the "text" field.
func (_c *IncidentCreate) SetText(v string) *IncidentCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *IncidentCreate) SetDescription(v string) *IncidentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableDescription(v *string) *IncidentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *IncidentCreate) SetStartDate(v time.Time) *IncidentCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *IncidentCreate) SetEndDate(v time.Time) *IncidentCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableEndDate(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetImpact sets the "impact" field.
func (_c *IncidentCreate) SetImpact(v int) *IncidentCreate {
	_c.mutation.SetImpact(v)
	return _c
}

// SetSystem sets the "system" field.
func (_c *IncidentCreate) SetSystem(v bool) *IncidentCreate {
	_c.mutation.SetSystem(v)
	return _c
}

// SetNillableSystem sets the "system" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableSystem(v *bool) *IncidentCreate {
	if v != nil {
		_c.SetSystem(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *IncidentCreate) SetType(v incident.Type) *IncidentCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IncidentCreate) SetStatus(v string) *IncidentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableStatus(v *string) *IncidentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IncidentCreate) SetCreatedAt(v time.Time) *IncidentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableCreatedAt(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetModifiedAt sets the "modified_at" field.
func (_c *IncidentCreate) SetModifiedAt(v time.Time) *IncidentCreate {
	_c.mutation.SetModifiedAt(v)
	return _c
}

// SetNillableModifiedAt sets the "modified_at" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableModifiedAt(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetModifiedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *IncidentCreate) SetDeletedAt(v time.Time) *IncidentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableDeletedAt(v *time.Time) *IncidentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *IncidentCreate) SetCreatedBy(v string) *IncidentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableCreatedBy(v *string) *IncidentCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *IncidentCreate) SetContactEmail(v string) *IncidentCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableContactEmail(v *string) *IncidentCreate {
	if v != nil {
		_c.SetContactEmail(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *IncidentCreate) SetVersion(v int) *IncidentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *IncidentCreate) SetNillableVersion(v *int) *IncidentCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IncidentCreate) SetID(v int) *IncidentCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddComponentIDs adds the "components" edge to the Component entity by IDs.
func (_c *IncidentCreate) AddComponentIDs(ids ...int) *IncidentCreate {
	_c.mutation.AddComponentIDs(ids...)
	return _c
}

// AddComponents adds the "components" edges to the Component entity.
func (_c *IncidentCreate) AddComponents(v ...*Component) *IncidentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddComponentIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the NotificationOutbox entity by IDs.
func (_c *IncidentCreate) AddNotificationIDs(ids ...int) *IncidentCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotifications adds the "notifications" edges to the NotificationOutbox entity.
func (_c *IncidentCreate) AddNotifications(v ...*NotificationOutbox) *IncidentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_c *IncidentCreate) Mutation() *IncidentMutation {
	return _c.mutation
}

// Save creates the Incident in the database.
func (_c *IncidentCreate) Save(ctx context.Context) (*Incident, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IncidentCreate) SaveX(ctx context.Context) *Incident {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IncidentCreate) defaults() {
	if _, ok := _c.mutation.System(); !ok {
		v := incident.DefaultSystem
		_c.mutation.SetSystem(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := incident.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IncidentCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Incident.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := incident.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Incident.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Incident.start_date"`)}
	}
	if _, ok := _c.mutation.Impact(); !ok {
		return &ValidationError{Name: "impact", err: errors.New(`ent: missing required field "Incident.impact"`)}
	}
	if _, ok := _c.mutation.System(); !ok {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required field "Incident.system"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Incident.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := incident.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Incident.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Incident.version"`)}
	}
	return nil
}

func (_c *IncidentCreate) sqlSave(ctx context.Context) (*Incident, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IncidentCreate) createSpec() (*Incident, *sqlgraph.CreateSpec) {
	var (
		_node = &Incident{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(incident.Table, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(incident.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(incident.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(incident.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(incident.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.Impact(); ok {
		_spec.SetField(incident.FieldImpact, field.TypeInt, value)
		_node.Impact = value
	}
	if value, ok := _c.mutation.System(); ok {
		_spec.SetField(incident.FieldSystem, field.TypeBool, value)
		_node.System = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(incident.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(incident.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(incident.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ModifiedAt(); ok {
		_spec.SetField(incident.FieldModifiedAt, field.TypeTime, value)
		_node.ModifiedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(incident.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(incident.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(incident.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(incident.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if nodes := _c.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.ComponentsTable,
			Columns: incident.ComponentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(component.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.NotificationsTable,
			Columns: []string{incident.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationoutbox.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Incident.Create().
//		SetText(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentUpsert) {
//			SetText(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentCreate) OnConflict(opts ...sql.ConflictOption) *IncidentUpsertOne {
	_c.conflict = opts
	return &IncidentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Incident.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentCreate) OnConflictColumns(columns ...string) *IncidentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentUpsertOne{
		create: _c,
	}
}

type (
	// IncidentUpsertOne is the builder for "upsert"-ing
	//  one Incident node.
	IncidentUpsertOne struct {
		create *IncidentCreate
	}

	// IncidentUpsert is the "OnConflict" setter.
	IncidentUpsert struct {
		*sql.UpdateSet
	}
)

// SetText sets the "text" field.
func (u *IncidentUpsert) SetText(v string) *IncidentUpsert {
	u.Set(incident.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateText() *IncidentUpsert {
	u.SetExcluded(incident.FieldText)
	return u
}

// SetDescription sets the "description" field.
func (u *IncidentUpsert) SetDescription(v string) *IncidentUpsert {
	u.Set(incident.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateDescription() *IncidentUpsert {
	u.SetExcluded(incident.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *IncidentUpsert) ClearDescription() *IncidentUpsert {
	u.SetNull(incident.FieldDescription)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *IncidentUpsert) SetStartDate(v time.Time) *IncidentUpsert {
	u.Set(incident.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateStartDate() *IncidentUpsert {
	u.SetExcluded(incident.FieldStartDate)
	return u
}

// SetEndDate sets the "end_date" field.
func (u *IncidentUpsert) SetEndDate(v time.Time) *IncidentUpsert {
	u.Set(incident.FieldEndDate, v)
	return u
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateEndDate() *IncidentUpsert {
	u.SetExcluded(incident.FieldEndDate)
	return u
}

// ClearEndDate clears the value of the "end_date" field.
func (u *IncidentUpsert) ClearEndDate() *IncidentUpsert {
	u.SetNull(incident.FieldEndDate)
	return u
}

// SetImpact sets the "impact" field.
func (u *IncidentUpsert) SetImpact(v int) *IncidentUpsert {
	u.Set(incident.FieldImpact, v)
	return u
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateImpact() *IncidentUpsert {
	u.SetExcluded(incident.FieldImpact)
	return u
}

// AddImpact adds v to the "impact" field.
func (u *IncidentUpsert) AddImpact(v int) *IncidentUpsert {
	u.Add(incident.FieldImpact, v)
	return u
}

// SetSystem sets the "system" field.
func (u *IncidentUpsert) SetSystem(v bool) *IncidentUpsert {
	u.Set(incident.FieldSystem, v)
	return u
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateSystem() *IncidentUpsert {
	u.SetExcluded(incident.FieldSystem)
	return u
}

// SetType sets the "type" field.
func (u *IncidentUpsert) SetType(v incident.Type) *IncidentUpsert {
	u.Set(incident.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateType() *IncidentUpsert {
	u.SetExcluded(incident.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *IncidentUpsert) SetStatus(v string) *IncidentUpsert {
	u.Set(incident.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateStatus() *IncidentUpsert {
	u.SetExcluded(incident.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *IncidentUpsert) ClearStatus() *IncidentUpsert {
	u.SetNull(incident.FieldStatus)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentUpsert) SetCreatedAt(v time.Time) *IncidentUpsert {
	u.Set(incident.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateCreatedAt() *IncidentUpsert {
	u.SetExcluded(incident.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentUpsert) ClearCreatedAt() *IncidentUpsert {
	u.SetNull(incident.FieldCreatedAt)
	return u
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentUpsert) SetModifiedAt(v time.Time) *IncidentUpsert {
	u.Set(incident.FieldModifiedAt, v)
	return u
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateModifiedAt() *IncidentUpsert {
	u.SetExcluded(incident.FieldModifiedAt)
	return u
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentUpsert) ClearModifiedAt() *IncidentUpsert {
	u.SetNull(incident.FieldModifiedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentUpsert) SetDeletedAt(v time.Time) *IncidentUpsert {
	u.Set(incident.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateDeletedAt() *IncidentUpsert {
	u.SetExcluded(incident.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentUpsert) ClearDeletedAt() *IncidentUpsert {
	u.SetNull(incident.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentUpsert) SetCreatedBy(v string) *IncidentUpsert {
	u.Set(incident.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateCreatedBy() *IncidentUpsert {
	u.SetExcluded(incident.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentUpsert) ClearCreatedBy() *IncidentUpsert {
	u.SetNull(incident.FieldCreatedBy)
	return u
}

// SetContactEmail sets the "contact_email" field.
func (u *IncidentUpsert) SetContactEmail(v string) *IncidentUpsert {
	u.Set(incident.FieldContactEmail, v)
	return u
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateContactEmail() *IncidentUpsert {
	u.SetExcluded(incident.FieldContactEmail)
	return u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *IncidentUpsert) ClearContactEmail() *IncidentUpsert {
	u.SetNull(incident.FieldContactEmail)
	return u
}

// SetVersion sets the "version" field.
func (u *IncidentUpsert) SetVersion(v int) *IncidentUpsert {
	u.Set(incident.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IncidentUpsert) UpdateVersion() *IncidentUpsert {
	u.SetExcluded(incident.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *IncidentUpsert) AddVersion(v int) *IncidentUpsert {
	u.Add(incident.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Incident.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(incident.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IncidentUpsertOne) UpdateNewValues() *IncidentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(incident.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Incident.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IncidentUpsertOne) Ignore() *IncidentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentUpsertOne) DoNothing() *IncidentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentCreate.OnConflict
// documentation for more info.
func (u *IncidentUpsertOne) Update(set func(*IncidentUpsert)) *IncidentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentUpsert{UpdateSet: update})
	}))
	return u
}

// SetText sets the "text" field.
func (u *IncidentUpsertOne) SetText(v string) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateText() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateText()
	})
}

// SetDescription sets the "description" field.
func (u *IncidentUpsertOne) SetDescription(v string) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateDescription() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *IncidentUpsertOne) ClearDescription() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearDescription()
	})
}

// SetStartDate sets the "start_date" field.
func (u *IncidentUpsertOne) SetStartDate(v time.Time) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateStartDate() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *IncidentUpsertOne) SetEndDate(v time.Time) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateEndDate() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateEndDate()
	})
}

// ClearEndDate clears the value of the "end_date" field.
func (u *IncidentUpsertOne) ClearEndDate() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearEndDate()
	})
}

// SetImpact sets the "impact" field.
func (u *IncidentUpsertOne) SetImpact(v int) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetImpact(v)
	})
}

// AddImpact adds v to the "impact" field.
func (u *IncidentUpsertOne) AddImpact(v int) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.AddImpact(v)
	})
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateImpact() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateImpact()
	})
}

// SetSystem sets the "system" field.
func (u *IncidentUpsertOne) SetSystem(v bool) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateSystem() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateSystem()
	})
}

// SetType sets the "type" field.
func (u *IncidentUpsertOne) SetType(v incident.Type) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateType() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *IncidentUpsertOne) SetStatus(v string) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateStatus() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *IncidentUpsertOne) ClearStatus() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentUpsertOne) SetCreatedAt(v time.Time) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateCreatedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentUpsertOne) ClearCreatedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentUpsertOne) SetModifiedAt(v time.Time) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateModifiedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentUpsertOne) ClearModifiedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentUpsertOne) SetDeletedAt(v time.Time) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateDeletedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentUpsertOne) ClearDeletedAt() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentUpsertOne) SetCreatedBy(v string) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateCreatedBy() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentUpsertOne) ClearCreatedBy() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearCreatedBy()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *IncidentUpsertOne) SetContactEmail(v string) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateContactEmail() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateContactEmail()
	})
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *IncidentUpsertOne) ClearContactEmail() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearContactEmail()
	})
}

// SetVersion sets the "version" field.
func (u *IncidentUpsertOne) SetVersion(v int) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *IncidentUpsertOne) AddVersion(v int) *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IncidentUpsertOne) UpdateVersion() *IncidentUpsertOne {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *IncidentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IncidentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IncidentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IncidentCreateBulk is the builder for creating many Incident entities in bulk.
type IncidentCreateBulk struct {
	config
	err      error
	builders []*IncidentCreate
	conflict []sql.ConflictOption
}

// Save creates the Incident entities in the database.
func (_c *IncidentCreateBulk) Save(ctx context.Context) ([]*Incident, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Incident, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncidentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IncidentCreateBulk) SaveX(ctx context.Context) []*Incident {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Incident.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentUpsert) {
//			SetText(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentCreateBulk) OnConflict(opts ...sql.ConflictOption) *IncidentUpsertBulk {
	_c.conflict = opts
	return &IncidentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Incident.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentCreateBulk) OnConflictColumns(columns ...string) *IncidentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentUpsertBulk{
		create: _c,
	}
}

// IncidentUpsertBulk is the builder for "upsert"-ing
// a bulk of Incident nodes.
type IncidentUpsertBulk struct {
	create *IncidentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Incident.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(incident.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IncidentUpsertBulk) UpdateNewValues() *IncidentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(incident.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Incident.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IncidentUpsertBulk) Ignore() *IncidentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentUpsertBulk) DoNothing() *IncidentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentCreateBulk.OnConflict
// documentation for more info.
func (u *IncidentUpsertBulk) Update(set func(*IncidentUpsert)) *IncidentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentUpsert{UpdateSet: update})
	}))
	return u
}

// SetText sets the "text" field.
func (u *IncidentUpsertBulk) SetText(v string) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateText() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateText()
	})
}

// SetDescription sets the "description" field.
func (u *IncidentUpsertBulk) SetDescription(v string) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateDescription() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *IncidentUpsertBulk) ClearDescription() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearDescription()
	})
}

// SetStartDate sets the "start_date" field.
func (u *IncidentUpsertBulk) SetStartDate(v time.Time) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateStartDate() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *IncidentUpsertBulk) SetEndDate(v time.Time) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateEndDate() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateEndDate()
	})
}

// ClearEndDate clears the value of the "end_date" field.
func (u *IncidentUpsertBulk) ClearEndDate() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearEndDate()
	})
}

// SetImpact sets the "impact" field.
func (u *IncidentUpsertBulk) SetImpact(v int) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetImpact(v)
	})
}

// AddImpact adds v to the "impact" field.
func (u *IncidentUpsertBulk) AddImpact(v int) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.AddImpact(v)
	})
}

// UpdateImpact sets the "impact" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateImpact() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateImpact()
	})
}

// SetSystem sets the "system" field.
func (u *IncidentUpsertBulk) SetSystem(v bool) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetSystem(v)
	})
}

// UpdateSystem sets the "system" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateSystem() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateSystem()
	})
}

// SetType sets the "type" field.
func (u *IncidentUpsertBulk) SetType(v incident.Type) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateType() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *IncidentUpsertBulk) SetStatus(v string) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateStatus() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *IncidentUpsertBulk) ClearStatus() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IncidentUpsertBulk) SetCreatedAt(v time.Time) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateCreatedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IncidentUpsertBulk) ClearCreatedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearCreatedAt()
	})
}

// SetModifiedAt sets the "modified_at" field.
func (u *IncidentUpsertBulk) SetModifiedAt(v time.Time) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetModifiedAt(v)
	})
}

// UpdateModifiedAt sets the "modified_at" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateModifiedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateModifiedAt()
	})
}

// ClearModifiedAt clears the value of the "modified_at" field.
func (u *IncidentUpsertBulk) ClearModifiedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearModifiedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *IncidentUpsertBulk) SetDeletedAt(v time.Time) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateDeletedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *IncidentUpsertBulk) ClearDeletedAt() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IncidentUpsertBulk) SetCreatedBy(v string) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateCreatedBy() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *IncidentUpsertBulk) ClearCreatedBy() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearCreatedBy()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *IncidentUpsertBulk) SetContactEmail(v string) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateContactEmail() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateContactEmail()
	})
}

// ClearContactEmail clears the value of the "contact_email" field.
func (u *IncidentUpsertBulk) ClearContactEmail() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.ClearContactEmail()
	})
}

// SetVersion sets the "version" field.
func (u *IncidentUpsertBulk) SetVersion(v int) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *IncidentUpsertBulk) AddVersion(v int) *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *IncidentUpsertBulk) UpdateVersion() *IncidentUpsertBulk {
	return u.Update(func(s *IncidentUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *IncidentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IncidentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
