// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// NotificationOutboxDelete is the builder for deleting a NotificationOutbox entity.
type NotificationOutboxDelete struct {
	config
	hooks    []Hook
	mutation *NotificationOutboxMutation
}

// Where appends a list predicates to the NotificationOutboxDelete builder.
func (_d *NotificationOutboxDelete) Where(ps ...predicate.NotificationOutbox) *NotificationOutboxDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotificationOutboxDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationOutboxDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotificationOutboxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationoutbox.Table, sqlgraph.NewFieldSpec(notificationoutbox.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotificationOutboxDeleteOne is the builder for deleting a single NotificationOutbox entity.
type NotificationOutboxDeleteOne struct {
	_d *NotificationOutboxDelete
}

// Where appends a list predicates to the NotificationOutboxDelete builder.
func (_d *NotificationOutboxDeleteOne) Where(ps ...predicate.NotificationOutbox) *NotificationOutboxDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotificationOutboxDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationoutbox.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationOutboxDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
