// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// NotificationOutboxUpdate is the builder for updating NotificationOutbox entities.
type NotificationOutboxUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationOutboxMutation
}

// Where appends a list predicates to the NotificationOutboxUpdate builder.
func (_u *NotificationOutboxUpdate) Where(ps ...predicate.NotificationOutbox) *NotificationOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *NotificationOutboxUpdate) SetKind(v string) *NotificationOutboxUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableKind(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *NotificationOutboxUpdate) SetIncidentID(v int) *NotificationOutboxUpdate {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableIncidentID(v *int) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *NotificationOutboxUpdate) SetRecipient(v string) *NotificationOutboxUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableRecipient(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *NotificationOutboxUpdate) SetPayload(v map[string]interface{}) *NotificationOutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *NotificationOutboxUpdate) SetChangeID(v string) *NotificationOutboxUpdate {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableChangeID(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetDedupKey sets the "dedup_key" field.
func (_u *NotificationOutboxUpdate) SetDedupKey(v string) *NotificationOutboxUpdate {
	_u.mutation.SetDedupKey(v)
	return _u
}

// SetNillableDedupKey sets the "dedup_key" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableDedupKey(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetDedupKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationOutboxUpdate) SetStatus(v string) *NotificationOutboxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableStatus(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *NotificationOutboxUpdate) SetAttempts(v int) *NotificationOutboxUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableAttempts(v *int) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *NotificationOutboxUpdate) AddAttempts(v int) *NotificationOutboxUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *NotificationOutboxUpdate) SetNextAttemptAt(v time.Time) *NotificationOutboxUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableNextAttemptAt(v *time.Time) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *NotificationOutboxUpdate) ClearNextAttemptAt() *NotificationOutboxUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *NotificationOutboxUpdate) SetLockedBy(v string) *NotificationOutboxUpdate {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableLockedBy(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *NotificationOutboxUpdate) ClearLockedBy() *NotificationOutboxUpdate {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *NotificationOutboxUpdate) SetLockedAt(v time.Time) *NotificationOutboxUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableLockedAt(v *time.Time) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *NotificationOutboxUpdate) ClearLockedAt() *NotificationOutboxUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationOutboxUpdate) SetLastError(v string) *NotificationOutboxUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableLastError(v *string) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *NotificationOutboxUpdate) ClearLastError() *NotificationOutboxUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationOutboxUpdate) SetCreatedAt(v time.Time) *NotificationOutboxUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableCreatedAt(v *time.Time) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationOutboxUpdate) SetUpdatedAt(v time.Time) *NotificationOutboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdate) SetNillableUpdatedAt(v *time.Time) *NotificationOutboxUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *NotificationOutboxUpdate) SetIncident(v *Incident) *NotificationOutboxUpdate {
	return _u.SetIncidentID(v.ID)
}

// Mutation returns the NotificationOutboxMutation object of the builder.
func (_u *NotificationOutboxUpdate) Mutation() *NotificationOutboxMutation {
	return _u.mutation
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *NotificationOutboxUpdate) ClearIncident() *NotificationOutboxUpdate {
	_u.mutation.ClearIncident()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationOutboxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationOutboxUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationoutbox.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := notificationoutbox.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.recipient": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeID(); ok {
		if err := notificationoutbox.ChangeIDValidator(v); err != nil {
			return &ValidationError{Name: "change_id", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.change_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupKey(); ok {
		if err := notificationoutbox.DedupKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedup_key", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.dedup_key": %w`, err)}
		}
	}
	if _u.mutation.IncidentCleared() && len(_u.mutation.IncidentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationOutbox.incident"`)
	}
	return nil
}

func (_u *NotificationOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationoutbox.Table, notificationoutbox.Columns, sqlgraph.NewFieldSpec(notificationoutbox.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationoutbox.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(notificationoutbox.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(notificationoutbox.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ChangeID(); ok {
		_spec.SetField(notificationoutbox.FieldChangeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DedupKey(); ok {
		_spec.SetField(notificationoutbox.FieldDedupKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(notificationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(notificationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(notificationoutbox.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(notificationoutbox.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(notificationoutbox.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(notificationoutbox.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(notificationoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(notificationoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notificationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(notificationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationoutbox.IncidentTable,
			Columns: []string{notificationoutbox.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationoutbox.IncidentTable,
			Columns: []string{notificationoutbox.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationOutboxUpdateOne is the builder for updating a single NotificationOutbox entity.
type NotificationOutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationOutboxMutation
}

// SetKind sets the "kind" field.
func (_u *NotificationOutboxUpdateOne) SetKind(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableKind(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetIncidentID sets the "incident_id" field.
func (_u *NotificationOutboxUpdateOne) SetIncidentID(v int) *NotificationOutboxUpdateOne {
	_u.mutation.SetIncidentID(v)
	return _u
}

// SetNillableIncidentID sets the "incident_id" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableIncidentID(v *int) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetIncidentID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *NotificationOutboxUpdateOne) SetRecipient(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableRecipient(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *NotificationOutboxUpdateOne) SetPayload(v map[string]interface{}) *NotificationOutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetChangeID sets the "change_id" field.
func (_u *NotificationOutboxUpdateOne) SetChangeID(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetChangeID(v)
	return _u
}

// SetNillableChangeID sets the "change_id" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableChangeID(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetChangeID(*v)
	}
	return _u
}

// SetDedupKey sets the "dedup_key" field.
func (_u *NotificationOutboxUpdateOne) SetDedupKey(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetDedupKey(v)
	return _u
}

// SetNillableDedupKey sets the "dedup_key" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableDedupKey(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetDedupKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationOutboxUpdateOne) SetStatus(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableStatus(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *NotificationOutboxUpdateOne) SetAttempts(v int) *NotificationOutboxUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableAttempts(v *int) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *NotificationOutboxUpdateOne) AddAttempts(v int) *NotificationOutboxUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *NotificationOutboxUpdateOne) SetNextAttemptAt(v time.Time) *NotificationOutboxUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableNextAttemptAt(v *time.Time) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *NotificationOutboxUpdateOne) ClearNextAttemptAt() *NotificationOutboxUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetLockedBy sets the "locked_by" field.
func (_u *NotificationOutboxUpdateOne) SetLockedBy(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetLockedBy(v)
	return _u
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableLockedBy(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetLockedBy(*v)
	}
	return _u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (_u *NotificationOutboxUpdateOne) ClearLockedBy() *NotificationOutboxUpdateOne {
	_u.mutation.ClearLockedBy()
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *NotificationOutboxUpdateOne) SetLockedAt(v time.Time) *NotificationOutboxUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableLockedAt(v *time.Time) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *NotificationOutboxUpdateOne) ClearLockedAt() *NotificationOutboxUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotificationOutboxUpdateOne) SetLastError(v string) *NotificationOutboxUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableLastError(v *string) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *NotificationOutboxUpdateOne) ClearLastError() *NotificationOutboxUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NotificationOutboxUpdateOne) SetCreatedAt(v time.Time) *NotificationOutboxUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableCreatedAt(v *time.Time) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationOutboxUpdateOne) SetUpdatedAt(v time.Time) *NotificationOutboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *NotificationOutboxUpdateOne) SetNillableUpdatedAt(v *time.Time) *NotificationOutboxUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_u *NotificationOutboxUpdateOne) SetIncident(v *Incident) *NotificationOutboxUpdateOne {
	return _u.SetIncidentID(v.ID)
}

// Mutation returns the NotificationOutboxMutation object of the builder.
func (_u *NotificationOutboxUpdateOne) Mutation() *NotificationOutboxMutation {
	return _u.mutation
}

// ClearIncident clears the "incident" edge to the Incident entity.
func (_u *NotificationOutboxUpdateOne) ClearIncident() *NotificationOutboxUpdateOne {
	_u.mutation.ClearIncident()
	return _u
}

// Where appends a list predicates to the NotificationOutboxUpdate builder.
func (_u *NotificationOutboxUpdateOne) Where(ps ...predicate.NotificationOutbox) *NotificationOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationOutboxUpdateOne) Select(field string, fields ...string) *NotificationOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationOutbox entity.
func (_u *NotificationOutboxUpdateOne) Save(ctx context.Context) (*NotificationOutbox, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationOutboxUpdateOne) SaveX(ctx context.Context) *NotificationOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationOutboxUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := notificationoutbox.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := notificationoutbox.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.recipient": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChangeID(); ok {
		if err := notificationoutbox.ChangeIDValidator(v); err != nil {
			return &ValidationError{Name: "change_id", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.change_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DedupKey(); ok {
		if err := notificationoutbox.DedupKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedup_key", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.dedup_key": %w`, err)}
		}
	}
	if _u.mutation.IncidentCleared() && len(_u.mutation.IncidentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationOutbox.incident"`)
	}
	return nil
}

func (_u *NotificationOutboxUpdateOne) sqlSave(ctx context.Context) (_node *NotificationOutbox, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationoutbox.Table, notificationoutbox.Columns, sqlgraph.NewFieldSpec(notificationoutbox.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationoutbox.FieldID)
		for _, f := range fields {
			if !notificationoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(notificationoutbox.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(notificationoutbox.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(notificationoutbox.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ChangeID(); ok {
		_spec.SetField(notificationoutbox.FieldChangeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DedupKey(); ok {
		_spec.SetField(notificationoutbox.FieldDedupKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(notificationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(notificationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(notificationoutbox.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(notificationoutbox.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockedBy(); ok {
		_spec.SetField(notificationoutbox.FieldLockedBy, field.TypeString, value)
	}
	if _u.mutation.LockedByCleared() {
		_spec.ClearField(notificationoutbox.FieldLockedBy, field.TypeString)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(notificationoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(notificationoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notificationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(notificationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationoutbox.IncidentTable,
			Columns: []string{notificationoutbox.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationoutbox.IncidentTable,
			Columns: []string{notificationoutbox.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
