// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
)

// NotificationOutbox is the model entity for the NotificationOutbox schema.
type NotificationOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// IncidentID holds the value of the "incident_id" field.
	IncidentID int `json:"incident_id,omitempty"`
	// Recipient holds the value of the "recipient" field.
	Recipient string `json:"recipient,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// ChangeID holds the value of the "change_id" field.
	ChangeID string `json:"change_id,omitempty"`
	// DedupKey holds the value of the "dedup_key" field.
	DedupKey string `json:"dedup_key,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// LockedBy holds the value of the "locked_by" field.
	LockedBy string `json:"locked_by,omitempty"`
	// LockedAt holds the value of the "locked_at" field.
	LockedAt time.Time `json:"locked_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationOutboxQuery when eager-loading is set.
	Edges        NotificationOutboxEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationOutboxEdges holds the relations/edges for other nodes in the graph.
type NotificationOutboxEdges struct {
	// Incident holds the value of the incident edge.
	Incident *Incident `json:"incident,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IncidentOrErr returns the Incident value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationOutboxEdges) IncidentOrErr() (*Incident, error) {
	if e.Incident != nil {
		return e.Incident, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: incident.Label}
	}
	return nil, &NotLoadedError{edge: "incident"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationoutbox.FieldPayload:
			values[i] = new([]byte)
		case notificationoutbox.FieldID, notificationoutbox.FieldIncidentID, notificationoutbox.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case notificationoutbox.FieldKind, notificationoutbox.FieldRecipient, notificationoutbox.FieldChangeID, notificationoutbox.FieldDedupKey, notificationoutbox.FieldStatus, notificationoutbox.FieldLockedBy, notificationoutbox.FieldLastError:
			values[i] = new(sql.NullString)
		case notificationoutbox.FieldNextAttemptAt, notificationoutbox.FieldLockedAt, notificationoutbox.FieldCreatedAt, notificationoutbox.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationOutbox fields.
func (_m *NotificationOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationoutbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case notificationoutbox.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case notificationoutbox.FieldIncidentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field incident_id", values[i])
			} else if value.Valid {
				_m.IncidentID = int(value.Int64)
			}
		case notificationoutbox.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				_m.Recipient = value.String
			}
		case notificationoutbox.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case notificationoutbox.FieldChangeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_id", values[i])
			} else if value.Valid {
				_m.ChangeID = value.String
			}
		case notificationoutbox.FieldDedupKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dedup_key", values[i])
			} else if value.Valid {
				_m.DedupKey = value.String
			}
		case notificationoutbox.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case notificationoutbox.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case notificationoutbox.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case notificationoutbox.FieldLockedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locked_by", values[i])
			} else if value.Valid {
				_m.LockedBy = value.String
			}
		case notificationoutbox.FieldLockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_at", values[i])
			} else if value.Valid {
				_m.LockedAt = value.Time
			}
		case notificationoutbox.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case notificationoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationoutbox.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIncident queries the "incident" edge of the NotificationOutbox entity.
func (_m *NotificationOutbox) QueryIncident() *IncidentQuery {
	return NewNotificationOutboxClient(_m.config).QueryIncident(_m)
}

// Update returns a builder for updating this NotificationOutbox.
// Note that you need to call NotificationOutbox.Unwrap() before calling this method if this NotificationOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationOutbox) Update() *NotificationOutboxUpdateOne {
	return NewNotificationOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationOutbox) Unwrap() *NotificationOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("incident_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IncidentID))
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(_m.Recipient)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("change_id=")
	builder.WriteString(_m.ChangeID)
	builder.WriteString(", ")
	builder.WriteString("dedup_key=")
	builder.WriteString(_m.DedupKey)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("locked_by=")
	builder.WriteString(_m.LockedBy)
	builder.WriteString(", ")
	builder.WriteString("locked_at=")
	builder.WriteString(_m.LockedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NotificationOutboxes is a parsable slice of NotificationOutbox.
type NotificationOutboxes []*NotificationOutbox
