// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
)

// NotificationOutboxCreate is the builder for creating a NotificationOutbox entity.
type NotificationOutboxCreate struct {
	config
	mutation *NotificationOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKind sets the "kind" field.
func (_c *NotificationOutboxCreate) SetKind(v string) *NotificationOutboxCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetIncidentID sets the "incident_id" field.
func (_c *NotificationOutboxCreate) SetIncidentID(v int) *NotificationOutboxCreate {
	_c.mutation.SetIncidentID(v)
	return _c
}

// SetRecipient sets the "recipient" field.
func (_c *NotificationOutboxCreate) SetRecipient(v string) *NotificationOutboxCreate {
	_c.mutation.SetRecipient(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *NotificationOutboxCreate) SetPayload(v map[string]interface{}) *NotificationOutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetChangeID sets the "change_id" field.
func (_c *NotificationOutboxCreate) SetChangeID(v string) *NotificationOutboxCreate {
	_c.mutation.SetChangeID(v)
	return _c
}

// SetDedupKey sets the "dedup_key" field.
func (_c *NotificationOutboxCreate) SetDedupKey(v string) *NotificationOutboxCreate {
	_c.mutation.SetDedupKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationOutboxCreate) SetStatus(v string) *NotificationOutboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableStatus(v *string) *NotificationOutboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *NotificationOutboxCreate) SetAttempts(v int) *NotificationOutboxCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableAttempts(v *int) *NotificationOutboxCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *NotificationOutboxCreate) SetNextAttemptAt(v time.Time) *NotificationOutboxCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableNextAttemptAt(v *time.Time) *NotificationOutboxCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLockedBy sets the "locked_by" field.
func (_c *NotificationOutboxCreate) SetLockedBy(v string) *NotificationOutboxCreate {
	_c.mutation.SetLockedBy(v)
	return _c
}

// SetNillableLockedBy sets the "locked_by" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableLockedBy(v *string) *NotificationOutboxCreate {
	if v != nil {
		_c.SetLockedBy(*v)
	}
	return _c
}

// SetLockedAt sets the "locked_at" field.
func (_c *NotificationOutboxCreate) SetLockedAt(v time.Time) *NotificationOutboxCreate {
	_c.mutation.SetLockedAt(v)
	return _c
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableLockedAt(v *time.Time) *NotificationOutboxCreate {
	if v != nil {
		_c.SetLockedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *NotificationOutboxCreate) SetLastError(v string) *NotificationOutboxCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *NotificationOutboxCreate) SetNillableLastError(v *string) *NotificationOutboxCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationOutboxCreate) SetCreatedAt(v time.Time) *NotificationOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationOutboxCreate) SetUpdatedAt(v time.Time) *NotificationOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationOutboxCreate) SetID(v int) *NotificationOutboxCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetIncident sets the "incident" edge to the Incident entity.
func (_c *NotificationOutboxCreate) SetIncident(v *Incident) *NotificationOutboxCreate {
	return _c.SetIncidentID(v.ID)
}

// Mutation returns the NotificationOutboxMutation object of the builder.
func (_c *NotificationOutboxCreate) Mutation() *NotificationOutboxMutation {
	return _c.mutation
}

// Save creates the NotificationOutbox in the database.
func (_c *NotificationOutboxCreate) Save(ctx context.Context) (*NotificationOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationOutboxCreate) SaveX(ctx context.Context) *NotificationOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationOutboxCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := notificationoutbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := notificationoutbox.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationOutboxCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "NotificationOutbox.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := notificationoutbox.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IncidentID(); !ok {
		return &ValidationError{Name: "incident_id", err: errors.New(`ent: missing required field "NotificationOutbox.incident_id"`)}
	}
	if _, ok := _c.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "NotificationOutbox.recipient"`)}
	}
	if v, ok := _c.mutation.Recipient(); ok {
		if err := notificationoutbox.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.recipient": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "NotificationOutbox.payload"`)}
	}
	if _, ok := _c.mutation.ChangeID(); !ok {
		return &ValidationError{Name: "change_id", err: errors.New(`ent: missing required field "NotificationOutbox.change_id"`)}
	}
	if v, ok := _c.mutation.ChangeID(); ok {
		if err := notificationoutbox.ChangeIDValidator(v); err != nil {
			return &ValidationError{Name: "change_id", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.change_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DedupKey(); !ok {
		return &ValidationError{Name: "dedup_key", err: errors.New(`ent: missing required field "NotificationOutbox.dedup_key"`)}
	}
	if v, ok := _c.mutation.DedupKey(); ok {
		if err := notificationoutbox.DedupKeyValidator(v); err != nil {
			return &ValidationError{Name: "dedup_key", err: fmt.Errorf(`ent: validator failed for field "NotificationOutbox.dedup_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NotificationOutbox.status"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "NotificationOutbox.attempts"`)}
	}
	if len(_c.mutation.IncidentIDs()) == 0 {
		return &ValidationError{Name: "incident", err: errors.New(`ent: missing required edge "NotificationOutbox.incident"`)}
	}
	return nil
}

func (_c *NotificationOutboxCreate) sqlSave(ctx context.Context) (*NotificationOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationOutboxCreate) createSpec() (*NotificationOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationoutbox.Table, sqlgraph.NewFieldSpec(notificationoutbox.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(notificationoutbox.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Recipient(); ok {
		_spec.SetField(notificationoutbox.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(notificationoutbox.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.ChangeID(); ok {
		_spec.SetField(notificationoutbox.FieldChangeID, field.TypeString, value)
		_node.ChangeID = value
	}
	if value, ok := _c.mutation.DedupKey(); ok {
		_spec.SetField(notificationoutbox.FieldDedupKey, field.TypeString, value)
		_node.DedupKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notificationoutbox.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(notificationoutbox.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(notificationoutbox.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := _c.mutation.LockedBy(); ok {
		_spec.SetField(notificationoutbox.FieldLockedBy, field.TypeString, value)
		_node.LockedBy = &value
	}
	if value, ok := _c.mutation.LockedAt(); ok {
		_spec.SetField(notificationoutbox.FieldLockedAt, field.TypeTime, value)
		_node.LockedAt = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(notificationoutbox.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.IncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationoutbox.IncidentTable,
			Columns: []string{notificationoutbox.IncidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IncidentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationOutbox.Create().
//		SetKind(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationOutboxUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationOutboxCreate) OnConflict(opts ...sql.ConflictOption) *NotificationOutboxUpsertOne {
	_c.conflict = opts
	return &NotificationOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationOutboxCreate) OnConflictColumns(columns ...string) *NotificationOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationOutboxUpsertOne{
		create: _c,
	}
}

type (
	// NotificationOutboxUpsertOne is the builder for "upsert"-ing
	//  one NotificationOutbox node.
	NotificationOutboxUpsertOne struct {
		create *NotificationOutboxCreate
	}

	// NotificationOutboxUpsert is the "OnConflict" setter.
	NotificationOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetKind sets the "kind" field.
func (u *NotificationOutboxUpsert) SetKind(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateKind() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldKind)
	return u
}

// SetIncidentID sets the "incident_id" field.
func (u *NotificationOutboxUpsert) SetIncidentID(v int) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldIncidentID, v)
	return u
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateIncidentID() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldIncidentID)
	return u
}

// SetRecipient sets the "recipient" field.
func (u *NotificationOutboxUpsert) SetRecipient(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldRecipient, v)
	return u
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateRecipient() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldRecipient)
	return u
}

// SetPayload sets the "payload" field.
func (u *NotificationOutboxUpsert) SetPayload(v map[string]interface{}) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdatePayload() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldPayload)
	return u
}

// SetChangeID sets the "change_id" field.
func (u *NotificationOutboxUpsert) SetChangeID(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldChangeID, v)
	return u
}

// UpdateChangeID sets the "change_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateChangeID() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldChangeID)
	return u
}

// SetDedupKey sets the "dedup_key" field.
func (u *NotificationOutboxUpsert) SetDedupKey(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldDedupKey, v)
	return u
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateDedupKey() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldDedupKey)
	return u
}

// SetStatus sets the "status" field.
func (u *NotificationOutboxUpsert) SetStatus(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateStatus() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldStatus)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *NotificationOutboxUpsert) SetAttempts(v int) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateAttempts() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *NotificationOutboxUpsert) AddAttempts(v int) *NotificationOutboxUpsert {
	u.Add(notificationoutbox.FieldAttempts, v)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *NotificationOutboxUpsert) SetNextAttemptAt(v time.Time) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateNextAttemptAt() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldNextAttemptAt)
	return u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *NotificationOutboxUpsert) ClearNextAttemptAt() *NotificationOutboxUpsert {
	u.SetNull(notificationoutbox.FieldNextAttemptAt)
	return u
}

// SetLockedBy sets the "locked_by" field.
func (u *NotificationOutboxUpsert) SetLockedBy(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldLockedBy, v)
	return u
}

// UpdateLockedBy sets the "locked_by" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateLockedBy() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldLockedBy)
	return u
}

// ClearLockedBy clears the value of the "locked_by" field.
func (u *NotificationOutboxUpsert) ClearLockedBy() *NotificationOutboxUpsert {
	u.SetNull(notificationoutbox.FieldLockedBy)
	return u
}

// SetLockedAt sets the "locked_at" field.
func (u *NotificationOutboxUpsert) SetLockedAt(v time.Time) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldLockedAt, v)
	return u
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateLockedAt() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldLockedAt)
	return u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *NotificationOutboxUpsert) ClearLockedAt() *NotificationOutboxUpsert {
	u.SetNull(notificationoutbox.FieldLockedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *NotificationOutboxUpsert) SetLastError(v string) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateLastError() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *NotificationOutboxUpsert) ClearLastError() *NotificationOutboxUpsert {
	u.SetNull(notificationoutbox.FieldLastError)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationOutboxUpsert) SetCreatedAt(v time.Time) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateCreatedAt() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationOutboxUpsert) SetUpdatedAt(v time.Time) *NotificationOutboxUpsert {
	u.Set(notificationoutbox.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsert) UpdateUpdatedAt() *NotificationOutboxUpsert {
	u.SetExcluded(notificationoutbox.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationoutbox.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationOutboxUpsertOne) UpdateNewValues() *NotificationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationoutbox.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationOutboxUpsertOne) Ignore() *NotificationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationOutboxUpsertOne) DoNothing() *NotificationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationOutboxCreate.OnConflict
// documentation for more info.
func (u *NotificationOutboxUpsertOne) Update(set func(*NotificationOutboxUpsert)) *NotificationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *NotificationOutboxUpsertOne) SetKind(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateKind() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateKind()
	})
}

// SetIncidentID sets the "incident_id" field.
func (u *NotificationOutboxUpsertOne) SetIncidentID(v int) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetIncidentID(v)
	})
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateIncidentID() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateIncidentID()
	})
}

// SetRecipient sets the "recipient" field.
func (u *NotificationOutboxUpsertOne) SetRecipient(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetRecipient(v)
	})
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateRecipient() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateRecipient()
	})
}

// SetPayload sets the "payload" field.
func (u *NotificationOutboxUpsertOne) SetPayload(v map[string]interface{}) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdatePayload() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdatePayload()
	})
}

// SetChangeID sets the "change_id" field.
func (u *NotificationOutboxUpsertOne) SetChangeID(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetChangeID(v)
	})
}

// UpdateChangeID sets the "change_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateChangeID() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateChangeID()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *NotificationOutboxUpsertOne) SetDedupKey(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateDedupKey() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateDedupKey()
	})
}

// SetStatus sets the "status" field.
func (u *NotificationOutboxUpsertOne) SetStatus(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateStatus() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *NotificationOutboxUpsertOne) SetAttempts(v int) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *NotificationOutboxUpsertOne) AddAttempts(v int) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateAttempts() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *NotificationOutboxUpsertOne) SetNextAttemptAt(v time.Time) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateNextAttemptAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *NotificationOutboxUpsertOne) ClearNextAttemptAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLockedBy sets the "locked_by" field.
func (u *NotificationOutboxUpsertOne) SetLockedBy(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLockedBy(v)
	})
}

// UpdateLockedBy sets the "locked_by" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateLockedBy() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLockedBy()
	})
}

// ClearLockedBy clears the value of the "locked_by" field.
func (u *NotificationOutboxUpsertOne) ClearLockedBy() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLockedBy()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *NotificationOutboxUpsertOne) SetLockedAt(v time.Time) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateLockedAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *NotificationOutboxUpsertOne) ClearLockedAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLockedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *NotificationOutboxUpsertOne) SetLastError(v string) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateLastError() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *NotificationOutboxUpsertOne) ClearLastError() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationOutboxUpsertOne) SetCreatedAt(v time.Time) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateCreatedAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationOutboxUpsertOne) SetUpdatedAt(v time.Time) *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertOne) UpdateUpdatedAt() *NotificationOutboxUpsertOne {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationOutboxUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationOutboxUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationOutboxCreateBulk is the builder for creating many NotificationOutbox entities in bulk.
type NotificationOutboxCreateBulk struct {
	config
	err      error
	builders []*NotificationOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationOutbox entities in the database.
func (_c *NotificationOutboxCreateBulk) Save(ctx context.Context) ([]*NotificationOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationOutboxCreateBulk) SaveX(ctx context.Context) []*NotificationOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationOutboxUpsert) {
//			SetKind(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationOutboxUpsertBulk {
	_c.conflict = opts
	return &NotificationOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationOutboxCreateBulk) OnConflictColumns(columns ...string) *NotificationOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationOutboxUpsertBulk{
		create: _c,
	}
}

// NotificationOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationOutbox nodes.
type NotificationOutboxUpsertBulk struct {
	create *NotificationOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationoutbox.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationOutboxUpsertBulk) UpdateNewValues() *NotificationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationoutbox.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationOutboxUpsertBulk) Ignore() *NotificationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationOutboxUpsertBulk) DoNothing() *NotificationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationOutboxUpsertBulk) Update(set func(*NotificationOutboxUpsert)) *NotificationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetKind sets the "kind" field.
func (u *NotificationOutboxUpsertBulk) SetKind(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateKind() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateKind()
	})
}

// SetIncidentID sets the "incident_id" field.
func (u *NotificationOutboxUpsertBulk) SetIncidentID(v int) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetIncidentID(v)
	})
}

// UpdateIncidentID sets the "incident_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateIncidentID() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateIncidentID()
	})
}

// SetRecipient sets the "recipient" field.
func (u *NotificationOutboxUpsertBulk) SetRecipient(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetRecipient(v)
	})
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateRecipient() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateRecipient()
	})
}

// SetPayload sets the "payload" field.
func (u *NotificationOutboxUpsertBulk) SetPayload(v map[string]interface{}) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdatePayload() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdatePayload()
	})
}

// SetChangeID sets the "change_id" field.
func (u *NotificationOutboxUpsertBulk) SetChangeID(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetChangeID(v)
	})
}

// UpdateChangeID sets the "change_id" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateChangeID() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateChangeID()
	})
}

// SetDedupKey sets the "dedup_key" field.
func (u *NotificationOutboxUpsertBulk) SetDedupKey(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetDedupKey(v)
	})
}

// UpdateDedupKey sets the "dedup_key" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateDedupKey() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateDedupKey()
	})
}

// SetStatus sets the "status" field.
func (u *NotificationOutboxUpsertBulk) SetStatus(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateStatus() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *NotificationOutboxUpsertBulk) SetAttempts(v int) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *NotificationOutboxUpsertBulk) AddAttempts(v int) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateAttempts() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *NotificationOutboxUpsertBulk) SetNextAttemptAt(v time.Time) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateNextAttemptAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (u *NotificationOutboxUpsertBulk) ClearNextAttemptAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearNextAttemptAt()
	})
}

// SetLockedBy sets the "locked_by" field.
func (u *NotificationOutboxUpsertBulk) SetLockedBy(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLockedBy(v)
	})
}

// UpdateLockedBy sets the "locked_by" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateLockedBy() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLockedBy()
	})
}

// ClearLockedBy clears the value of the "locked_by" field.
func (u *NotificationOutboxUpsertBulk) ClearLockedBy() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLockedBy()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *NotificationOutboxUpsertBulk) SetLockedAt(v time.Time) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateLockedAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *NotificationOutboxUpsertBulk) ClearLockedAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLockedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *NotificationOutboxUpsertBulk) SetLastError(v string) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateLastError() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *NotificationOutboxUpsertBulk) ClearLastError() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *NotificationOutboxUpsertBulk) SetCreatedAt(v time.Time) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateCreatedAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotificationOutboxUpsertBulk) SetUpdatedAt(v time.Time) *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotificationOutboxUpsertBulk) UpdateUpdatedAt() *NotificationOutboxUpsertBulk {
	return u.Update(func(s *NotificationOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *NotificationOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
