// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/stackmon/otc-status-dashboard/ent/component"
	"github.com/stackmon/otc-status-dashboard/ent/componentattr"
	"github.com/stackmon/otc-status-dashboard/ent/incident"
	"github.com/stackmon/otc-status-dashboard/ent/incidentstatus"
	"github.com/stackmon/otc-status-dashboard/ent/notificationoutbox"
	"github.com/stackmon/otc-status-dashboard/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	componentFields := schema.Component{}.Fields()
	_ = componentFields
	// componentDescName is the schema descriptor for name field.
	componentDescName := componentFields[1].Descriptor()
	// component.NameValidator is a validator for the "name" field. It is called by the builders before save.
	component.NameValidator = componentDescName.Validators[0].(func(string) error)
	componentattrFields := schema.ComponentAttr{}.Fields()
	_ = componentattrFields
	// componentattrDescName is the schema descriptor for name field.
	componentattrDescName := componentattrFields[2].Descriptor()
	// componentattr.NameValidator is a validator for the "name" field. It is called by the builders before save.
	componentattr.NameValidator = componentattrDescName.Validators[0].(func(string) error)
	// componentattrDescValue is the schema descriptor for value field.
	componentattrDescValue := componentattrFields[3].Descriptor()
	// componentattr.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	componentattr.ValueValidator = componentattrDescValue.Validators[0].(func(string) error)
	incidentFields := schema.Incident{}.Fields()
	_ = incidentFields
	// incidentDescText is the schema descriptor for text field.
	incidentDescText := incidentFields[1].Descriptor()
	// incident.TextValidator is a validator for the "text" field. It is called by the builders before save.
	incident.TextValidator = incidentDescText.Validators[0].(func(string) error)
	// incidentDescSystem is the schema descriptor for system field.
	incidentDescSystem := incidentFields[6].Descriptor()
	// incident.DefaultSystem holds the default value on creation for the system field.
	incident.DefaultSystem = incidentDescSystem.Default.(bool)
	// incidentDescVersion is the schema descriptor for version field.
	incidentDescVersion := incidentFields[14].Descriptor()
	// incident.DefaultVersion holds the default value on creation for the version field.
	incident.DefaultVersion = incidentDescVersion.Default.(int)
	incidentstatusFields := schema.IncidentStatus{}.Fields()
	_ = incidentstatusFields
	// incidentstatusDescText is the schema descriptor for text field.
	incidentstatusDescText := incidentstatusFields[3].Descriptor()
	// incidentstatus.TextValidator is a validator for the "text" field. It is called by the builders before save.
	incidentstatus.TextValidator = incidentstatusDescText.Validators[0].(func(string) error)
	// incidentstatusDescStatus is the schema descriptor for status field.
	incidentstatusDescStatus := incidentstatusFields[4].Descriptor()
	// incidentstatus.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	incidentstatus.StatusValidator = incidentstatusDescStatus.Validators[0].(func(string) error)
	notificationoutboxFields := schema.NotificationOutbox{}.Fields()
	_ = notificationoutboxFields
	// notificationoutboxDescKind is the schema descriptor for kind field.
	notificationoutboxDescKind := notificationoutboxFields[1].Descriptor()
	// notificationoutbox.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	notificationoutbox.KindValidator = notificationoutboxDescKind.Validators[0].(func(string) error)
	// notificationoutboxDescRecipient is the schema descriptor for recipient field.
	notificationoutboxDescRecipient := notificationoutboxFields[3].Descriptor()
	// notificationoutbox.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	notificationoutbox.RecipientValidator = notificationoutboxDescRecipient.Validators[0].(func(string) error)
	// notificationoutboxDescChangeID is the schema descriptor for change_id field.
	notificationoutboxDescChangeID := notificationoutboxFields[5].Descriptor()
	// notificationoutbox.ChangeIDValidator is a validator for the "change_id" field. It is called by the builders before save.
	notificationoutbox.ChangeIDValidator = notificationoutboxDescChangeID.Validators[0].(func(string) error)
	// notificationoutboxDescDedupKey is the schema descriptor for dedup_key field.
	notificationoutboxDescDedupKey := notificationoutboxFields[6].Descriptor()
	// notificationoutbox.DedupKeyValidator is a validator for the "dedup_key" field. It is called by the builders before save.
	notificationoutbox.DedupKeyValidator = notificationoutboxDescDedupKey.Validators[0].(func(string) error)
	// notificationoutboxDescStatus is the schema descriptor for status field.
	notificationoutboxDescStatus := notificationoutboxFields[7].Descriptor()
	// notificationoutbox.DefaultStatus holds the default value on creation for the status field.
	notificationoutbox.DefaultStatus = notificationoutboxDescStatus.Default.(string)
	// notificationoutboxDescAttempts is the schema descriptor for attempts field.
	notificationoutboxDescAttempts := notificationoutboxFields[8].Descriptor()
	// notificationoutbox.DefaultAttempts holds the default value on creation for the attempts field.
	notificationoutbox.DefaultAttempts = notificationoutboxDescAttempts.Default.(int)
}
