// Code generated by ent, DO NOT EDIT.

package notificationoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stackmon/otc-status-dashboard/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldID, id))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldKind, v))
}

// IncidentID applies equality check predicate on the "incident_id" field. It's identical to IncidentIDEQ.
func IncidentID(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldIncidentID, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldRecipient, v))
}

// ChangeID applies equality check predicate on the "change_id" field. It's identical to ChangeIDEQ.
func ChangeID(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldChangeID, v))
}

// DedupKey applies equality check predicate on the "dedup_key" field. It's identical to DedupKeyEQ.
func DedupKey(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldDedupKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldStatus, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldAttempts, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LockedBy applies equality check predicate on the "locked_by" field. It's identical to LockedByEQ.
func LockedBy(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLockedBy, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLockedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldKind, v))
}

// IncidentIDEQ applies the EQ predicate on the "incident_id" field.
func IncidentIDEQ(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldIncidentID, v))
}

// IncidentIDNEQ applies the NEQ predicate on the "incident_id" field.
func IncidentIDNEQ(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldIncidentID, v))
}

// IncidentIDIn applies the In predicate on the "incident_id" field.
func IncidentIDIn(vs ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldIncidentID, vs...))
}

// IncidentIDNotIn applies the NotIn predicate on the "incident_id" field.
func IncidentIDNotIn(vs ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldIncidentID, vs...))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldRecipient, v))
}

// ChangeIDEQ applies the EQ predicate on the "change_id" field.
func ChangeIDEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldChangeID, v))
}

// ChangeIDNEQ applies the NEQ predicate on the "change_id" field.
func ChangeIDNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldChangeID, v))
}

// ChangeIDIn applies the In predicate on the "change_id" field.
func ChangeIDIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldChangeID, vs...))
}

// ChangeIDNotIn applies the NotIn predicate on the "change_id" field.
func ChangeIDNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldChangeID, vs...))
}

// ChangeIDGT applies the GT predicate on the "change_id" field.
func ChangeIDGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldChangeID, v))
}

// ChangeIDGTE applies the GTE predicate on the "change_id" field.
func ChangeIDGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldChangeID, v))
}

// ChangeIDLT applies the LT predicate on the "change_id" field.
func ChangeIDLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldChangeID, v))
}

// ChangeIDLTE applies the LTE predicate on the "change_id" field.
func ChangeIDLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldChangeID, v))
}

// ChangeIDContains applies the Contains predicate on the "change_id" field.
func ChangeIDContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldChangeID, v))
}

// ChangeIDHasPrefix applies the HasPrefix predicate on the "change_id" field.
func ChangeIDHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldChangeID, v))
}

// ChangeIDHasSuffix applies the HasSuffix predicate on the "change_id" field.
func ChangeIDHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldChangeID, v))
}

// ChangeIDEqualFold applies the EqualFold predicate on the "change_id" field.
func ChangeIDEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldChangeID, v))
}

// ChangeIDContainsFold applies the ContainsFold predicate on the "change_id" field.
func ChangeIDContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldChangeID, v))
}

// DedupKeyEQ applies the EQ predicate on the "dedup_key" field.
func DedupKeyEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldDedupKey, v))
}

// DedupKeyNEQ applies the NEQ predicate on the "dedup_key" field.
func DedupKeyNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldDedupKey, v))
}

// DedupKeyIn applies the In predicate on the "dedup_key" field.
func DedupKeyIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldDedupKey, vs...))
}

// DedupKeyNotIn applies the NotIn predicate on the "dedup_key" field.
func DedupKeyNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldDedupKey, vs...))
}

// DedupKeyGT applies the GT predicate on the "dedup_key" field.
func DedupKeyGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldDedupKey, v))
}

// DedupKeyGTE applies the GTE predicate on the "dedup_key" field.
func DedupKeyGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldDedupKey, v))
}

// DedupKeyLT applies the LT predicate on the "dedup_key" field.
func DedupKeyLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldDedupKey, v))
}

// DedupKeyLTE applies the LTE predicate on the "dedup_key" field.
func DedupKeyLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldDedupKey, v))
}

// DedupKeyContains applies the Contains predicate on the "dedup_key" field.
func DedupKeyContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldDedupKey, v))
}

// DedupKeyHasPrefix applies the HasPrefix predicate on the "dedup_key" field.
func DedupKeyHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldDedupKey, v))
}

// DedupKeyHasSuffix applies the HasSuffix predicate on the "dedup_key" field.
func DedupKeyHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldDedupKey, v))
}

// DedupKeyEqualFold applies the EqualFold predicate on the "dedup_key" field.
func DedupKeyEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldDedupKey, v))
}

// DedupKeyContainsFold applies the ContainsFold predicate on the "dedup_key" field.
func DedupKeyContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldDedupKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldAttempts, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldNextAttemptAt, v))
}

// NextAttemptAtIsNil applies the IsNil predicate on the "next_attempt_at" field.
func NextAttemptAtIsNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIsNull(FieldNextAttemptAt))
}

// NextAttemptAtNotNil applies the NotNil predicate on the "next_attempt_at" field.
func NextAttemptAtNotNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotNull(FieldNextAttemptAt))
}

// LockedByEQ applies the EQ predicate on the "locked_by" field.
func LockedByEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLockedBy, v))
}

// LockedByNEQ applies the NEQ predicate on the "locked_by" field.
func LockedByNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldLockedBy, v))
}

// LockedByIn applies the In predicate on the "locked_by" field.
func LockedByIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldLockedBy, vs...))
}

// LockedByNotIn applies the NotIn predicate on the "locked_by" field.
func LockedByNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldLockedBy, vs...))
}

// LockedByGT applies the GT predicate on the "locked_by" field.
func LockedByGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldLockedBy, v))
}

// LockedByGTE applies the GTE predicate on the "locked_by" field.
func LockedByGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldLockedBy, v))
}

// LockedByLT applies the LT predicate on the "locked_by" field.
func LockedByLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldLockedBy, v))
}

// LockedByLTE applies the LTE predicate on the "locked_by" field.
func LockedByLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldLockedBy, v))
}

// LockedByContains applies the Contains predicate on the "locked_by" field.
func LockedByContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldLockedBy, v))
}

// LockedByHasPrefix applies the HasPrefix predicate on the "locked_by" field.
func LockedByHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldLockedBy, v))
}

// LockedByHasSuffix applies the HasSuffix predicate on the "locked_by" field.
func LockedByHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldLockedBy, v))
}

// LockedByIsNil applies the IsNil predicate on the "locked_by" field.
func LockedByIsNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIsNull(FieldLockedBy))
}

// LockedByNotNil applies the NotNil predicate on the "locked_by" field.
func LockedByNotNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotNull(FieldLockedBy))
}

// LockedByEqualFold applies the EqualFold predicate on the "locked_by" field.
func LockedByEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldLockedBy, v))
}

// LockedByContainsFold applies the ContainsFold predicate on the "locked_by" field.
func LockedByContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldLockedBy, v))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotNull(FieldLockedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasIncident applies the HasEdge predicate on the "incident" edge.
func HasIncident() predicate.NotificationOutbox {
	return predicate.NotificationOutbox(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IncidentTable, IncidentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncidentWith applies the HasEdge predicate on the "incident" edge with a given conditions (other predicates).
func HasIncidentWith(preds ...predicate.Incident) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(func(s *sql.Selector) {
		step := newIncidentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationOutbox) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationOutbox) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationOutbox) predicate.NotificationOutbox {
	return predicate.NotificationOutbox(sql.NotPredicates(p))
}
