// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Component is the predicate function for component builders.
type Component func(*sql.Selector)

// ComponentAttr is the predicate function for componentattr builders.
type ComponentAttr func(*sql.Selector)

// Incident is the predicate function for incident builders.
type Incident func(*sql.Selector)

// IncidentStatus is the predicate function for incidentstatus builders.
type IncidentStatus func(*sql.Selector)

// NotificationOutbox is the predicate function for notificationoutbox builders.
type NotificationOutbox func(*sql.Selector)
